# **EDA Notebook**

---
## 0. Setup Environment

In [69]:
# DO NOT MODIFY THE CODE IN THIS CELL
!pip install -q utstd

from utstd.folders import *
from utstd.ipyrenders import *

at = AtFolder(
    course_code=36106,
    assignment="AT3",
)
at.run()

import warnings
warnings.simplefilter(action='ignore')

WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
    WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: pip install --upgrade pip

WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
    WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
    WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)

You can now save your data files in: /Users/aryan/Machine Learning Assignment 3/36106/assignment/AT3/data

WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
utstd 0.1.8 requires scikit-learn~=1.5.1, but you have scikit-learn 1.6.1 which is incompatible.
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: pip install --upgrade pip
sh: import: command not found
sh: -c: line 0: syntax error near unexpected token `"ignore"'
sh: -c: line 0: `warnings.filterwarnings("ignore")'

---
## Student Information

In [70]:
# <Student to fill this section>
group_name = "36106-26AU-AT3-Group01"
student_name = "Aryan Goel"
student_id = "26040826"

In [71]:
# Do not modify this code
print_tile(size="h1", key='group_name', value=group_name)

In [72]:
# Do not modify this code
print_tile(size="h1", key='student_name', value=student_name)

In [73]:
# Do not modify this code
print_tile(size="h1", key='student_id', value=student_id)

---
## 0. Python Packages

### 0.a Install Additional Packages

> If you are using additional packages, you need to install them here using the command: `! pip install <package_name>`

In [74]:
# <Student to fill this section>

### 0.b Import Packages

In [75]:
# <Student to fill this section>
import pandas as pd
import altair as alt

---
## B. Data Understanding

In [76]:
# Do not modify this code
try:
  df = pd.read_csv(at.folder_path / "customer.csv")
except Exception as e:
  print(e)

### B.1 Explore Dataset

In [77]:
# B.1 Explore Dataset (customer.csv)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)

print("Customer dataset loaded:", isinstance(df, pd.DataFrame))
display(df.head(10))
display(df.tail(5))

# Basic structure
n_rows, n_cols = df.shape
print(f"Shape: {n_rows:,} rows x {n_cols:,} columns")

# Column types + non-null counts
info_df = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "non_null": df.notna().sum().values,
    "nulls": df.isna().sum().values,
    "null_%": (df.isna().mean() * 100).round(2).values,
    "n_unique": df.nunique(dropna=True).values
}).sort_values(["null_%", "n_unique"], ascending=[False, True])

display(info_df)

# Duplicates
dup_rows = df.duplicated().sum()
print(f"Duplicate rows: {dup_rows:,} ({dup_rows/n_rows*100:.2f}%)")

# Candidate ID-like columns (heuristic)
id_like = [c for c in df.columns if c.lower().endswith("id") or c.lower() in ("id", "customerid", "customer_id")]
print("ID-like columns:", id_like)

# Duplicates by ID (if any ID column exists)
for c in id_like:
    dup_id = df[c].duplicated().sum()
    print(f"Duplicated values in {c}: {dup_id:,} ({(dup_id/df[c].notna().sum()*100 if df[c].notna().sum()>0 else 0):.2f}%)")

# Numeric summary
num_cols = df.select_dtypes(include="number").columns.tolist()
if len(num_cols) > 0:
    display(df[num_cols].describe().T)

# Object/categorical summary (top categories)
cat_cols = df.select_dtypes(include=["object", "category", "bool"]).columns.tolist()
cat_preview = []
for c in cat_cols:
    vc = df[c].value_counts(dropna=False).head(10)
    cat_preview.append(pd.DataFrame({"column": c, "value": vc.index.astype(str), "count": vc.values}))
if len(cat_preview) > 0:
    display(pd.concat(cat_preview, ignore_index=True))

Customer dataset loaded: True

,customer_id,person_id,store_id,territory_id,account_number
0,4b5762b3-b7bf-4716-9bf9-5c1c9e1f375d,092707ff-4088-4416-ac86-14491f3120c2,NaN,0ad4c625-bb65-4376-8a41-0a65719b0db8,AW00019475
1,26bfba89-84b7-4b5b-9bab-caf7a2791006,fe043525-e0af-4578-a4b9-bfa7be28f4e4,NaN,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,AW00022390
2,cf2cf4cc-fcce-4fe5-9400-78373420b525,ee25bbaf-5cdd-4ed4-92fe-7136c4e803a9,NaN,0ad4c625-bb65-4376-8a41-0a65719b0db8,AW00016320
3,83f558b8-bdab-4781-b112-55d2c275ff52,f0452f05-3690-4170-9fb0-fbf9995bbea7,NaN,2ac923e9-3043-4f5e-bae0-ad28089bf187,AW00026149
4,5edc53f4-7821-4a9b-9c27-a45dd2af713e,16c2532d-adb6-4a33-b0ea-71b87d83a904,NaN,0ad4c625-bb65-4376-8a41-0a65719b0db8,AW00021849
5,afff0c06-ae08-4a75-af8b-84373ea48cc8,112ec726-3b23-4a89-a2df-3911fbd4ca68,NaN,2ac923e9-3043-4f5e-bae0-ad28089bf187,AW00015716
6,8cc00885-ba1b-4175-aaa7-fd0baaa626c7,012874dd-8dd8-437f-9068-31dec9cea44f,NaN,0ad4c625-bb65-4376-8a41-0a65719b0db8,AW00019323
7,0591a2f9-59d7-42d3-9a5a-f2f7b8cc7346,dc53b945-2b6e-42de-91c9-2ae812c2db49,NaN,0ad4c625-bb65-4376-8a41-0a65719b0db8,AW00013681
8,060c5593-b9c3-4c41-97bd-78040e780308,14efa819-55ca-4d1f-8c42-330a338d6b04,NaN,0ad4c625-bb65-4376-8a41-0a65719b0db8,AW00017771
9,63f2224d-97e8-4a11-9a38-2e26cdf9979c,1c059581-ea42-40f7-b34e-fca5cf5f7243,NaN,2ac923e9-3043-4f5e-bae0-ad28089bf187,AW00024276

,customer_id,person_id,store_id,territory_id,account_number
14270,ed815eee-e5f0-4e03-b706-4ce8d1a2dd7c,55d19600-3a17-4e4b-8863-b96427852de1,NaN,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,AW00028374
14271,648057a9-519f-4d05-b64d-bdc2faf4f0e9,27f522c2-06f4-437f-ab39-b92e6969c844,NaN,e0e3bac4-790e-4617-84b3-be0c2bdb7070,AW00014784
14272,c238748a-f4f8-49e9-b462-330d2f7b68d5,0418b76b-eeed-482c-b086-796ee1bcc2b4,NaN,e0e3bac4-790e-4617-84b3-be0c2bdb7070,AW00016294
14273,ceb62a8b-d407-47b1-a20f-40e0d6c8944b,5d8610e3-4705-4f84-abab-ab3521f105aa,NaN,e0e3bac4-790e-4617-84b3-be0c2bdb7070,AW00016321
14274,c1198f86-cf66-4bc1-8e7d-79b40c1db804,cd70a799-a1a2-43a3-b2dc-03b2bce437ed,NaN,0ad4c625-bb65-4376-8a41-0a65719b0db8,AW00019255

Shape: 14,275 rows x 5 columns

           column   dtype  non_null  nulls  null_%  n_unique
2        store_id  object       452  13823   96.83       160
1       person_id  object     14038    237    1.66      9232
3    territory_id  object     14275      0    0.00         4
4  account_number  object     14275      0    0.00      9392
0     customer_id  object     14275      0    0.00     10331

Duplicate rows: 3,944 (27.63%)
ID-like columns: ['customer_id', 'person_id', 'store_id', 'territory_id']
Duplicated values in customer_id: 3,944 (27.63%)
Duplicated values in person_id: 5,042 (35.92%)
Duplicated values in store_id: 14,114 (3122.57%)
Duplicated values in territory_id: 14,271 (99.97%)

            column                                 value  count
0      customer_id  874949cb-8236-4956-87e6-99e9bfa58ce7      3
1      customer_id  992f1dfa-f210-4087-893d-8b183772a6ab      3
2      customer_id  83ffecc2-6069-4669-aa96-ed38ddd2b94e      3
3      customer_id  c9d447f0-f6b9-403f-83b4-e47620d0d474      3
4      customer_id  9c3373b7-e914-4373-a61a-0f343a51a267      3
5      customer_id  f0f9e3e3-4220-4193-8ba1-29e445205dcf      3
6      customer_id  38e5802c-aae9-4a54-b899-0961cc0f4cd7      3
7      customer_id  b4cb096d-0c2a-4c08-b57a-236501967fe3      3
8      customer_id  01868e32-7493-4560-9457-1205abfdc223      3
9      customer_id  7470e5c0-35b7-438e-8e47-2bf816490951      3
10       person_id                                   nan    237
11       person_id  54c4fea3-015b-4a97-ae9a-c1eec134584a      4
12       person_id  7144ff94-b93a-45ef-adec-5cd13fe4bd1b      4
13       person_id  27a278ba-7a42-4b1f-b622-55197ca9dddd      4
14       person_id  edead1a8-544a-4232-a935-72eefb20d571      4
15       person_id  017a09a2-fd32-40e8-aabb-5c295b349f0e      4
16       person_id  104eccb6-6841-4931-a478-7428e4628475      4
17       person_id  a9442370-7b81-4815-b7e5-7b01301ddbd3      4
18       person_id  81c2252f-0fb1-4d07-8fb3-2a7c799be218      4
19       person_id  e1e64b89-4853-4dd1-8715-b807cc130c50      4
20        store_id                                   nan  13823
21        store_id  af39eeb6-feb3-4df5-a2f1-407ecdc01998      6
22        store_id  e0dd80fa-378f-4cd8-916a-bbec07c5a4f2      5
23        store_id  34df6cec-bfc2-493a-9260-7304805f11d6      5
24        store_id  d973dcfa-58f0-4659-9305-439cfbabc7cd      5
25        store_id  b4b0f743-12d6-4fff-99ae-b17a7300d04a      5
26        store_id  ea5901c7-f681-4276-a3d3-4cc4eee16707      5
27        store_id  f6f5fa00-f44d-439f-88ef-51dfcd15b687      5
28        store_id  72b5ea7a-0825-47c4-9017-88f01c86516c      4
29        store_id  7f8d6b72-4655-40d7-8498-0897282bfc66      4
30    territory_id  2ac923e9-3043-4f5e-bae0-ad28089bf187   5567
31    territory_id  e0e3bac4-790e-4617-84b3-be0c2bdb7070   3008
32    territory_id  25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2   2851
33    territory_id  0ad4c625-bb65-4376-8a41-0a65719b0db8   2849
34  account_number                            AW00016436      4
35  account_number                            AW00026850      4
36  account_number                            AW00011398      4
37  account_number                            AW00013251      4
38  account_number                            AW00022608      4
39  account_number                            AW00012130      4
40  account_number                            AW00014528      4
41  account_number                            AW00025630      4
42  account_number                            AW00019947      4
43  account_number                            AW00024113      4

In [78]:
# Missingness visualisation + quick data dictionary
missing = (df.isna().mean() * 100).round(2).reset_index()
missing.columns = ["column", "missing_pct"]
missing = missing.sort_values("missing_pct", ascending=False)

missing_chart = (
    alt.Chart(missing)
    .mark_bar()
    .encode(
        x=alt.X("missing_pct:Q", title="Missing values (%)"),
        y=alt.Y("column:N", sort="-x", title="Column"),
        tooltip=["column:N", "missing_pct:Q"]
    )
    .properties(title="Customer dataset: Missing values by column", width=700, height=400)
)

missing_chart

alt.Chart(...)

In [79]:
dataset_insights = f"""
Customer dataset overview (customer.csv)

1) Dimensions & structure
- The dataset contains {df.shape[0]:,} rows and {df.shape[1]:,} columns.
- This table appears to represent a customer-level entity (one row per customer is expected).
- A customer table is typically used as the “entity anchor” for customer analytics and for joining with transactional tables (e.g., sales_order_header) to create customer behaviour features such as purchase frequency and recency.

2) Data types & feature groups (high-level)
- The dataset includes a mix of identifier-like columns (e.g., columns ending with 'ID'), categorical attributes (string/object columns), and possibly numerical or flag fields.
- Identifier columns should not be directly used as model inputs (they can cause leakage or spurious learning), but they are critical for joining tables.

3) Data quality checks performed
- Missing value scan: computed missing counts and percentages for every column.
- Duplicate checks: calculated duplicate rows and duplicated values for ID-like columns (where present).
- Uniqueness scan: computed number of unique values per column to detect:
  - constant columns (n_unique=1) which add no predictive value,
  - near-unique columns (high-cardinality) that may require careful encoding (e.g., hashing/target encoding) or exclusion.

4) Potential issues & limitations (to consider in modelling)
- Missingness: columns with high missing rates may need imputation, “missing” category labels, or removal depending on business meaning.
- High-cardinality categories: may inflate feature space and risk overfitting if one-hot encoded; alternative encoders or grouping rare levels may be necessary.
- Duplicates: if customer IDs are duplicated, it may indicate:
  - multiple records per customer (data integration issue),
  - or that the true grain is not customer-level. This must be resolved before training.
- Temporal limitations: the customer table often lacks time context; behavioural modelling (e.g., “will buy again”) must be built using transaction dates from sales_order_header/order_detail.

5) How this supports Student A’s classification use case
- For classification, customer attributes can be used as “static” predictors, while orders tables create behavioural predictors (RFM features).
- This EDA establishes whether the customer table can reliably serve as a unique customer index and which features are suitable for joining and modelling.

6) Next steps from this EDA
- Confirm the customer key column used to join to sales_order_header.
- Decide which customer attributes are ethically and practically appropriate (avoid sensitive attributes, check fairness risk).
- Use transaction history to create label(s) such as re-order within next N days and features such as recency/frequency/monetary value.
"""

In [80]:
# Do not modify this code
print_tile(size="h3", key='dataset_insights', value=dataset_insights)

### B.2 Explore Feature of Interest `territory_id`

In [81]:
# B.2: Auto-pick a strong categorical feature to explore
cat_cols = df.select_dtypes(include=["object", "category", "bool"]).columns.tolist()

# Choose a categorical feature with low missingness and not too many unique values
candidate_meta = []
for c in cat_cols:
    miss = df[c].isna().mean()
    nun = df[c].nunique(dropna=True)
    candidate_meta.append((c, miss, nun))

cand = pd.DataFrame(candidate_meta, columns=["col", "missing_rate", "n_unique"])
# Keep columns with some variation but not extreme cardinality for plotting
cand = cand[(cand["n_unique"] >= 2) & (cand["n_unique"] <= 30)].sort_values(["missing_rate", "n_unique"], ascending=[True, False])

feature_1 = cand["col"].iloc[0] if len(cand) > 0 else (cat_cols[0] if len(cat_cols) > 0 else None)
print("Selected feature_1:", feature_1)

if feature_1 is not None:
    vc = (
        df[feature_1]
        .fillna("<<MISSING>>")
        .value_counts()
        .reset_index()
    )
    vc.columns = [feature_1, "count"]
    vc["percent"] = (vc["count"] / vc["count"].sum() * 100).round(2)

    display(vc)

    chart = (
        alt.Chart(vc)
        .mark_bar()
        .encode(
            x=alt.X("count:Q", title="Count"),
            y=alt.Y(f"{feature_1}:N", sort="-x", title=feature_1),
            tooltip=[alt.Tooltip(f"{feature_1}:N", title=feature_1), "count:Q", "percent:Q"]
        )
        .properties(title=f"Distribution of {feature_1}", width=700, height=350)
    )
    chart
else:
    print("No categorical/boolean feature found to explore in B.2.")

Selected feature_1: territory_id

                           territory_id  count  percent
0  2ac923e9-3043-4f5e-bae0-ad28089bf187   5567    39.00
1  e0e3bac4-790e-4617-84b3-be0c2bdb7070   3008    21.07
2  25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2   2851    19.97
3  0ad4c625-bb65-4376-8a41-0a65719b0db8   2849    19.96

In [82]:
# B.2 Extra: Data quality checks for territory_id
feature = "territory_id"

print("=== territory_id data quality ===")
print("Missing count:", df[feature].isna().sum())
print("Missing %:", round(df[feature].isna().mean() * 100, 4))

# Uniqueness / cardinality
print("Unique territories (dropna=True):", df[feature].nunique(dropna=True))

# If there is a customer key, check duplicates per territory
id_like = [c for c in df.columns if c.lower().endswith("id") or c.lower() in ("customerid", "customer_id", "id")]
print("ID-like columns detected:", id_like)

=== territory_id data quality ===
Missing count: 0
Missing %: 0.0
Unique territories (dropna=True): 4
ID-like columns detected: ['customer_id', 'person_id', 'store_id', 'territory_id']

In [83]:
# B.2 Extra: cleaner chart (percent) for territory_id
plot_df = territory_counts.copy()

chart = (
    alt.Chart(plot_df)
    .mark_bar()
    .encode(
        x=alt.X("percent:Q", title="Customers (%)"),
        y=alt.Y("territory_id:N", sort="-x", title="territory_id"),
        tooltip=["territory_id:N", "customer_count:Q", "percent:Q"]
    )
    .properties(title="Customer distribution by territory_id", width=700, height=300)
)

text = (
    alt.Chart(plot_df)
    .mark_text(align="left", dx=5)
    .encode(
        x="percent:Q",
        y=alt.Y("territory_id:N", sort="-x"),
        text=alt.Text("percent:Q", format=".2f")
    )
)

(chart + text)

alt.LayerChart(...)

In [84]:
# B.2 Extra: Missingness profile by territory for other columns
feature = "territory_id"

# Choose columns to audit (exclude the territory itself)
cols_to_check = [c for c in df.columns if c != feature]

# Compute missing % by territory for each column
miss_by_terr = (
    df.assign(territory_id=df[feature].fillna("<<MISSING>>"))
      .groupby("territory_id")[cols_to_check]
      .apply(lambda g: g.isna().mean() * 100)
)

miss_long = miss_by_terr.reset_index().melt(
    id_vars="territory_id",
    var_name="column",
    value_name="missing_pct"
)

# Show top missing columns overall (to keep it readable)
top_missing_cols = (
    miss_long.groupby("column")["missing_pct"].mean()
    .sort_values(ascending=False)
    .head(12)
    .index
)

miss_long_top = miss_long[miss_long["column"].isin(top_missing_cols)].copy()
miss_long_top["missing_pct"] = miss_long_top["missing_pct"].round(2)

display(miss_long_top.sort_values(["column", "territory_id"]))

heat = (
    alt.Chart(miss_long_top)
    .mark_rect()
    .encode(
        x=alt.X("territory_id:N", title="territory_id"),
        y=alt.Y("column:N", title="Column (top missing)"),
        color=alt.Color("missing_pct:Q", title="Missing %", scale=alt.Scale(scheme="reds")),
        tooltip=["territory_id:N", "column:N", "missing_pct:Q"]
    )
    .properties(title="Missingness by territory (top columns)", width=700, height=300)
)

heat

                            territory_id          column  missing_pct
12  0ad4c625-bb65-4376-8a41-0a65719b0db8  account_number         0.00
13  25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2  account_number         0.00
14  2ac923e9-3043-4f5e-bae0-ad28089bf187  account_number         0.00
15  e0e3bac4-790e-4617-84b3-be0c2bdb7070  account_number         0.00
0   0ad4c625-bb65-4376-8a41-0a65719b0db8     customer_id         0.00
1   25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2     customer_id         0.00
2   2ac923e9-3043-4f5e-bae0-ad28089bf187     customer_id         0.00
3   e0e3bac4-790e-4617-84b3-be0c2bdb7070     customer_id         0.00
4   0ad4c625-bb65-4376-8a41-0a65719b0db8       person_id         1.90
5   25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2       person_id         2.21
6   2ac923e9-3043-4f5e-bae0-ad28089bf187       person_id         1.13
7   e0e3bac4-790e-4617-84b3-be0c2bdb7070       person_id         1.89
8   0ad4c625-bb65-4376-8a41-0a65719b0db8        store_id        96.56
9   25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2        store_id        95.93
10  2ac923e9-3043-4f5e-bae0-ad28089bf187        store_id        97.90
11  e0e3bac4-790e-4617-84b3-be0c2bdb7070        store_id        95.98

alt.Chart(...)

In [85]:
# B.2 Extra: Numeric feature comparison by territory (boxplots)
feature = "territory_id"
num_cols = df.select_dtypes(include="number").columns.tolist()

print("Numeric columns:", num_cols)

# Pick up to 3 numeric columns with lowest missingness and non-trivial variance
num_meta = []
for c in num_cols:
    num_meta.append((c, df[c].isna().mean(), df[c].std(skipna=True)))
num_meta = pd.DataFrame(num_meta, columns=["col", "missing_rate", "std"]).sort_values(["missing_rate", "std"], ascending=[True, False])

selected_num = num_meta["col"].head(3).tolist()
print("Selected numeric columns for territory comparison:", selected_num)

if len(selected_num) > 0:
    long_num = (
        df.assign(territory_id=df[feature].fillna("<<MISSING>>"))[["territory_id"] + selected_num]
          .melt(id_vars="territory_id", var_name="numeric_feature", value_name="value")
          .dropna()
    )

    box = (
        alt.Chart(long_num)
        .mark_boxplot()
        .encode(
            x=alt.X("territory_id:N", title="territory_id"),
            y=alt.Y("value:Q", title="Value"),
            color=alt.Color("territory_id:N", legend=None),
            facet=alt.Facet("numeric_feature:N", columns=1, title="Numeric feature")
        )
        .properties(title="Numeric feature distributions by territory", width=700, height=180)
    )

    box
else:
    print("No numeric columns found to compare across territory_id.")

Numeric columns: []
Selected numeric columns for territory comparison: []
No numeric columns found to compare across territory_id.

In [86]:
# B.2 Extra: Summary stats by territory (for numeric columns)
feature = "territory_id"
num_cols = df.select_dtypes(include="number").columns.tolist()

if len(num_cols) > 0:
    summary = (
        df.assign(territory_id=df[feature].fillna("<<MISSING>>"))
          .groupby("territory_id")[num_cols]
          .agg(["count", "mean", "median", "std", "min", "max"])
    )

    # Make it easier to read (optional): show only first 2 numeric cols if there are many
    display(summary)
else:
    print("No numeric columns available for territory-level summaries.")

No numeric columns available for territory-level summaries.

In [87]:
feature_1_insights = f"""
Feature explored: {feature_1} (territory_id)

What the feature represents (business meaning)
- territory_id is a geographic / sales-territory identifier that links each customer to a territory.
- In a retail context, territory often captures differences in customer demographics, local demand, marketing strategies, store coverage, and logistics performance. This can directly influence purchasing behaviour and therefore is a relevant predictor for classification use cases such as “will the customer place another order”.

Distribution (what we observed)
- The distribution is concentrated in exactly 4 territories (based on the value counts output).
- Category proportions are:
  - 2ac923e9-3043-4f5e-bae0-ad28089bf187: 5,567 customers (39.00%)
  - e0e3bac4-790e-4617-84b3-be0c2bdb7070: 3,008 customers (21.07%)
  - 25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2: 2,851 customers (19.97%)
  - 0ad4c625-bb65-4376-8a41-0a65719b0db8: 2,849 customers (19.96%)
- This indicates a moderate class imbalance across territories (largest territory ~39%, smallest ~20%), but not an extreme imbalance.

Data quality considerations / limitations
- territory_id is an encoded identifier (UUID-like) and is not human-readable on its own. For reporting, it is better to join to the sales_territory table (Student D EDA) to obtain interpretable territory names/regions.
- Because it is categorical with only 4 unique values, it is safe to one-hot encode without blowing up feature space.
- If territory assignment changes over time (not visible in this static customer table), it could introduce temporal inconsistency. For time-based modelling, we should confirm whether territory_id is stable or whether it is updated.

Modelling implication for Student A (classification)
- territory_id is a strong candidate feature because it can proxy for region-level purchasing patterns and operational differences.
- However, it should not be relied upon alone; it should be combined with behavioural features engineered from sales_order_header (e.g., recency, frequency, monetary value) to achieve high predictive power.
- If the target is “re-order in next N days”, territory_id can help capture baseline propensity differences between regions, and may improve calibration and recall for under-represented territories.

Ethical / fairness note (report-ready)
- Using territory can unintentionally act as a proxy for socioeconomic factors. We should evaluate model performance by territory segment (e.g., compare recall/precision per territory) to ensure the model does not systematically disadvantage customers in specific regions (e.g., by under-targeting them for retention offers).
"""

In [88]:
# Do not modify this code
print_tile(size="h3", key='feature_1_insights', value=feature_1_insights)

### B.3 Explore Feature of Interest `customer_id`

In [89]:
# B.3 Updated: Explore customer_id (ID integrity + join-readiness)

feature_2 = "customer_id"
print("Selected feature_2:", feature_2)

if feature_2 not in df.columns:
    raise ValueError(f"Column '{feature_2}' not found in dataframe. Available columns: {df.columns.tolist()}")

# 1) Coverage / missingness
total_rows = len(df)
missing_cnt = df[feature_2].isna().sum()
missing_pct = round(missing_cnt / total_rows * 100, 4)
print(f"Rows: {total_rows:,}")
print(f"Missing {feature_2}: {missing_cnt:,} ({missing_pct}%)")

# 2) Uniqueness / duplicates
n_unique = df[feature_2].nunique(dropna=True)
dup_cnt = df[feature_2].duplicated().sum()
print(f"Unique {feature_2} (dropna=True): {n_unique:,}")
print(f"Duplicated {feature_2} values: {dup_cnt:,}")

# Show example duplicated IDs (if any)
if dup_cnt > 0:
    dup_examples = (
        df[df[feature_2].duplicated(keep=False)][feature_2]
        .value_counts()
        .reset_index()
        .head(10)
    )
    dup_examples.columns = [feature_2, "repeat_count"]
    print("Top duplicated customer_id values (sample):")
    display(dup_examples)

# 3) Sanity checks on format/length (UUID-like profiling)
id_profile = df[[feature_2]].copy()
id_profile["is_missing"] = id_profile[feature_2].isna()
id_profile["as_str"] = id_profile[feature_2].astype(str)
id_profile["length"] = id_profile["as_str"].str.len()
id_profile["looks_uuid"] = id_profile["as_str"].str.fullmatch(
    r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
).fillna(False)

display(id_profile[["is_missing", "length", "looks_uuid"]].describe(include="all"))

fmt_summary = pd.DataFrame({
    "metric": ["min_length", "max_length", "most_common_length", "uuid_like_%"],
    "value": [
        int(id_profile.loc[~id_profile["is_missing"], "length"].min()) if (~id_profile["is_missing"]).any() else None,
        int(id_profile.loc[~id_profile["is_missing"], "length"].max()) if (~id_profile["is_missing"]).any() else None,
        int(id_profile.loc[~id_profile["is_missing"], "length"].mode().iloc[0]) if (~id_profile["is_missing"]).any() else None,
        round(id_profile.loc[~id_profile["is_missing"], "looks_uuid"].mean() * 100, 2) if (~id_profile["is_missing"]).any() else None
    ]
})
display(fmt_summary)

# 4) Visualise ID length distribution (helps detect inconsistent formats)
length_counts = (
    id_profile.loc[~id_profile["is_missing"], "length"]
    .value_counts()
    .reset_index()
)
length_counts.columns = ["id_length", "count"]
length_counts["percent"] = (length_counts["count"] / length_counts["count"].sum() * 100).round(2)
display(length_counts.sort_values("id_length"))

alt.Chart(length_counts).mark_bar().encode(
    x=alt.X("id_length:O", title="customer_id string length"),
    y=alt.Y("count:Q", title="Count"),
    tooltip=["id_length:O", "count:Q", "percent:Q"]
).properties(title="customer_id format check: length distribution", width=700, height=280)

Selected feature_2: customer_id
Rows: 14,275
Missing customer_id: 0 (0.0%)
Unique customer_id (dropna=True): 10,331
Duplicated customer_id values: 3,944
Top duplicated customer_id values (sample):

                            customer_id  repeat_count
0  7470e5c0-35b7-438e-8e47-2bf816490951             3
1  c253c0e7-d32f-40c3-b358-4b265159be84             3
2  2ca81f1d-0772-463c-abf6-cee6d749b6af             3
3  8ce33725-b0c2-4d85-97a7-90a2a2008b86             3
4  7e33a938-0c0c-4eef-a0b9-457667d5cdee             3
5  783cedfb-8336-47cc-a6e2-7d06156028d2             3
6  9a75e29a-700a-4946-91e4-9749912a3334             3
7  ab0b6eca-0794-4f79-8bea-40aa7bfa04fc             3
8  f652133e-4102-4c52-8694-8636de9d9594             3
9  83c6f949-91db-4dd6-9394-53f1349a7d45             3

       is_missing   length looks_uuid
count       14275  14275.0      14275
unique          1      NaN          1
top         False      NaN       True
freq        14275      NaN      14275
mean          NaN     36.0        NaN
std           NaN      0.0        NaN
min           NaN     36.0        NaN
25%           NaN     36.0        NaN
50%           NaN     36.0        NaN
75%           NaN     36.0        NaN
max           NaN     36.0        NaN

               metric  value
0          min_length   36.0
1          max_length   36.0
2  most_common_length   36.0
3         uuid_like_%  100.0

   id_length  count  percent
0         36  14275    100.0

alt.Chart(...)

In [90]:
# B.3 Extra 1: Verify table grain is 1 row per customer_id
feature = "customer_id"

rows = len(df)
unique_ids = df[feature].nunique(dropna=True)
dup_rows = rows - unique_ids

print(f"Rows: {rows:,}")
print(f"Unique customer_id: {unique_ids:,}")
print(f"Extra rows beyond unique customers (potential duplicates): {dup_rows:,}")

# If duplicates exist, show how many times IDs repeat
if df[feature].duplicated().any():
    rep = (
        df[feature].value_counts(dropna=False)
        .reset_index()
    )
    rep.columns = [feature, "row_count"]
    rep["row_count"] = rep["row_count"].astype(int)

    print("Distribution of repeated customer_id (top 20):")
    display(rep.sort_values("row_count", ascending=False).head(20))

    rep_dist = (
        rep.groupby("row_count")
           .size()
           .reset_index(name="n_customers")
           .sort_values("row_count")
    )
    display(rep_dist)

    alt.Chart(rep_dist).mark_bar().encode(
        x=alt.X("row_count:O", title="Rows per customer_id"),
        y=alt.Y("n_customers:Q", title="Number of customers"),
        tooltip=["row_count:O", "n_customers:Q"]
    ).properties(title="How many rows exist per customer_id?", width=700, height=250)
else:
    print("No duplicated customer_id values found. Grain is consistent with one row per customer.")

Rows: 14,275
Unique customer_id: 10,331
Extra rows beyond unique customers (potential duplicates): 3,944
Distribution of repeated customer_id (top 20):

                              customer_id  row_count
0    874949cb-8236-4956-87e6-99e9bfa58ce7          3
228  aeb2ee42-c07d-46ac-bff3-9991b78c00d7          3
236  bb3c53a7-d3ac-4aeb-b6de-7b45513858d6          3
235  d25358cd-303c-4de0-b5bc-a590a5f6bfde          3
234  db435820-a19a-47b8-b91d-087beb81b8fd          3
233  03f6dfff-61be-4173-a2f9-dc7bfe710689          3
232  2cbd7f66-94c0-4947-82c9-86790cab287c          3
231  63f329bc-4199-425e-9562-b51d7bbd1623          3
230  442fccca-655a-43e3-ac3e-e4b0567a6428          3
229  77328c83-74c6-40fc-82f8-da655d0ac91f          3
227  11ede76e-1b10-493e-be91-62b49170fbb6          3
238  c253c0e7-d32f-40c3-b358-4b265159be84          3
226  973dc7dd-50f7-4e5b-8e75-4f930c2d310e          3
225  a1235116-6847-461d-8c40-b38dc88949b6          3
224  cd77f236-b326-4096-8e55-ae40e743cb4f          3
223  d9145963-3b5a-4f2b-813d-c3d7564385e4          3
222  83e79586-f86e-4c14-9191-ce834298bf4f          3
221  007e46ce-58c3-41ee-99d3-b632818f1974          3
220  86f31212-5144-421d-b1a3-19e45c0b7410          3
219  acd032ec-c7a1-4a1e-9288-5b32482ebfe6          3

   row_count  n_customers
0          1         6733
1          2         3252
2          3          346

In [91]:
# B.3 Extra 2: If customer_id duplicates exist, check whether duplicates are identical or conflicting
feature = "customer_id"

if df[feature].duplicated().any():
    dup_df = df[df[feature].duplicated(keep=False)].copy()

    print("Duplicated customer_id rows:", dup_df.shape[0])
    print("Duplicated customer_id unique IDs:", dup_df[feature].nunique())

    # For each customer_id, count how many columns have >1 unique value (conflicts)
    conflict_cols = []
    for c in df.columns:
        if c == feature:
            continue
        g = dup_df.groupby(feature)[c].nunique(dropna=False)
        conflict_cols.append((c, (g > 1).sum()))

    conflict_summary = (
        pd.DataFrame(conflict_cols, columns=["column", "n_customer_ids_with_conflict"])
        .sort_values("n_customer_ids_with_conflict", ascending=False)
    )
    display(conflict_summary.head(30))

    # Show sample conflicting customer_ids for the most conflicting column
    top_conflict_col = conflict_summary.iloc[0]["column"] if len(conflict_summary) else None
    if top_conflict_col and conflict_summary.iloc[0]["n_customer_ids_with_conflict"] > 0:
        bad_ids = (
            dup_df.groupby(feature)[top_conflict_col].nunique(dropna=False)
            .loc[lambda s: s > 1]
            .index[:5]
        )
        print(f"Sample customer_ids with conflicting '{top_conflict_col}':")
        display(dup_df[dup_df[feature].isin(bad_ids)].sort_values(feature).head(50))
else:
    print("No duplicate customer_id values; skipping duplicate conflict analysis.")

Duplicated customer_id rows: 7542
Duplicated customer_id unique IDs: 3598

           column  n_customer_ids_with_conflict
0       person_id                             0
1        store_id                             0
2    territory_id                             0
3  account_number                             0

In [92]:
# B.3 Extra 3: Exact duplicate row check (excluding customer_id)
feature = "customer_id"
cols_except_id = [c for c in df.columns if c != feature]

exact_dups = df.duplicated(subset=cols_except_id).sum()
print(f"Exact duplicate rows (excluding {feature}): {exact_dups:,}")

if exact_dups > 0:
    display(df[df.duplicated(subset=cols_except_id, keep=False)].head(20))

Exact duplicate rows (excluding customer_id): 4,883

,customer_id,person_id,store_id,territory_id,account_number
0,4b5762b3-b7bf-4716-9bf9-5c1c9e1f375d,092707ff-4088-4416-ac86-14491f3120c2,NaN,0ad4c625-bb65-4376-8a41-0a65719b0db8,AW00019475
1,26bfba89-84b7-4b5b-9bab-caf7a2791006,fe043525-e0af-4578-a4b9-bfa7be28f4e4,NaN,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,AW00022390
2,cf2cf4cc-fcce-4fe5-9400-78373420b525,ee25bbaf-5cdd-4ed4-92fe-7136c4e803a9,NaN,0ad4c625-bb65-4376-8a41-0a65719b0db8,AW00016320
5,afff0c06-ae08-4a75-af8b-84373ea48cc8,112ec726-3b23-4a89-a2df-3911fbd4ca68,NaN,2ac923e9-3043-4f5e-bae0-ad28089bf187,AW00015716
7,0591a2f9-59d7-42d3-9a5a-f2f7b8cc7346,dc53b945-2b6e-42de-91c9-2ae812c2db49,NaN,0ad4c625-bb65-4376-8a41-0a65719b0db8,AW00013681
8,060c5593-b9c3-4c41-97bd-78040e780308,14efa819-55ca-4d1f-8c42-330a338d6b04,NaN,0ad4c625-bb65-4376-8a41-0a65719b0db8,AW00017771
9,63f2224d-97e8-4a11-9a38-2e26cdf9979c,1c059581-ea42-40f7-b34e-fca5cf5f7243,NaN,2ac923e9-3043-4f5e-bae0-ad28089bf187,AW00024276
10,1d7e655a-5178-4ceb-ad95-a9ae6a7f7c17,7e2f05be-668d-4452-8b2c-66d01c645be2,NaN,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,AW00012870
12,6e1b128b-3d3b-425b-b430-df32a0cb2964,18c45a0c-e85b-4e39-a312-c693a85713f3,NaN,2ac923e9-3043-4f5e-bae0-ad28089bf187,AW00023415
16,c551007e-5675-473f-9cd1-2786ac075880,466b333a-a441-4522-8726-ae9b85d7b110,NaN,e0e3bac4-790e-4617-84b3-be0c2bdb7070,AW00022671
17,17075390-8d8a-44d2-b8dd-802f5eb5ef58,f536e011-e86d-4673-92a9-6a1ce37c334e,NaN,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,AW00025508
18,b3d8419b-d440-443e-8a5b-be7d10e9c90d,a0ec4e76-fc93-4e82-932d-a2e61f0e0b57,NaN,2ac923e9-3043-4f5e-bae0-ad28089bf187,AW00015727
19,6519fd57-67e9-490c-9007-61f4d65c2cbe,69f6e9bb-c0a0-4acb-a229-5ee1f3846b0b,NaN,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,AW00029356
20,6c0dbd35-e262-4842-927a-5d16ed195644,13d3ece9-c5b4-4d18-a0ee-1f6aa4aa7852,NaN,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,AW00027777
21,d1c076ba-a626-40b3-b138-e0ea1836c1d1,8b92476b-2bf9-4156-b8ca-b5da49fb3fb8,NaN,e0e3bac4-790e-4617-84b3-be0c2bdb7070,AW00021669
22,0f4e73ff-471d-4fb0-a046-545e0eb1f06f,1c8b343b-80c5-4404-8475-c83d5f73c9e3,NaN,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,AW00015113
23,dfb4aae2-3e3a-4650-bdd3-64c9a3a7fdca,ea7c2908-9b9d-4d2d-995a-5bb2a5262da3,NaN,2ac923e9-3043-4f5e-bae0-ad28089bf187,AW00013969
24,36cf3677-b70b-42d2-91ca-786f6c6498f9,73b90499-39a9-4b4f-8085-3b3ba78bfa60,NaN,e0e3bac4-790e-4617-84b3-be0c2bdb7070,AW00013692
25,20c4eab7-6cb0-4f96-a860-49aebbf228f6,530f0a04-a395-4239-906a-502568151d6d,NaN,e0e3bac4-790e-4617-84b3-be0c2bdb7070,AW00012334
26,9afb632c-d4aa-4dcb-944a-dda7017ba15c,dc499ea0-8413-4a12-bff8-940851f6fb9a,NaN,e0e3bac4-790e-4617-84b3-be0c2bdb7070,AW00020839

In [93]:
# B.3 Extra 4: Compare missingness between duplicated and non-duplicated customer_id rows
feature = "customer_id"

df_tmp = df.copy()
df_tmp["is_customer_id_duplicated"] = df_tmp[feature].duplicated(keep=False)

missing_rate_by_group = (
    df_tmp.groupby("is_customer_id_duplicated")
          .apply(lambda g: (g.isna().mean() * 100).round(2))
)

display(missing_rate_by_group.T.sort_values(by=True, ascending=False).head(25))

is_customer_id_duplicated  False  True
store_id                   96.66  96.99
person_id                   1.72   1.60
customer_id                 0.00   0.00
territory_id                0.00   0.00
account_number              0.00   0.00
is_customer_id_duplicated   0.00   0.00

In [94]:
# B.3 Extra 5: Consistency check - does a customer_id map to multiple territory_id values?
feature = "customer_id"
other = "territory_id"

if other in df.columns:
    terr_per_customer = df.groupby(feature)[other].nunique(dropna=False)
    multi_terr = (terr_per_customer > 1).sum()
    print(f"Customers with >1 territory_id: {multi_terr:,} out of {terr_per_customer.shape[0]:,}")

    if multi_terr > 0:
        example_ids = terr_per_customer[terr_per_customer > 1].index[:10].tolist()
        print("Example customer_ids with multiple territories:")
        display(df[df[feature].isin(example_ids)].sort_values(feature).head(50))
else:
    print("territory_id not found; skipping customer-territory consistency check.")

Customers with >1 territory_id: 0 out of 10,331

In [95]:
# B.3 Extra 6: Join-key / modelling readiness dictionary
def is_id_like(colname: str) -> bool:
    c = colname.lower()
    return c.endswith("id") or c in ("id", "customerid", "customer_id")

dd = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str),
    "missing_%": (df.isna().mean() * 100).round(2).values,
    "n_unique": [df[c].nunique(dropna=True) for c in df.columns],
    "id_like": [is_id_like(c) for c in df.columns]
}).sort_values(["id_like", "missing_%", "n_unique"], ascending=[False, False, False])

display(dd.head(30))

                        column   dtype  missing_%  n_unique  id_like
store_id              store_id  object      96.83       160     True
person_id            person_id  object       1.66      9232     True
customer_id        customer_id  object       0.00     10331     True
territory_id      territory_id  object       0.00         4     True
account_number  account_number  object       0.00      9392    False

In [96]:
# <Student to fill this section>
feature_2_insights = """
Feature explored: customer_id

What the feature represents (business meaning)
- customer_id is the primary customer identifier (a surrogate key). It is the most important field for:
  (1) confirming the grain of the customer table (ideally one row per customer),
  (2) joining customer attributes to transactional tables such as sales_order_header and sales_order_detail,
  (3) building customer-level behavioural features (recency, frequency, monetary value) for Student A’s classification use case.

What we analysed (EDA checks performed)
- Coverage: missing count and missing percentage for customer_id.
- Uniqueness: number of unique customer_id values and number of duplicated IDs.
- Duplicate pattern: how many rows exist per customer_id (to confirm whether the dataset is truly customer-level).
- Format sanity: basic checks such as string length distribution and whether IDs look UUID-like.
- Consistency checks (when duplicates exist): whether the same customer_id maps to multiple territory_id values and whether duplicate rows contain conflicting attribute values.

Key observations (how to interpret your outputs)
- If customer_id has ~0% missingness and ~0 duplicated values:
  - The table is consistent with a “one row per customer” grain, making it reliable as the base table for modelling.
- If duplicates exist:
  - If duplicates are exact copies (no conflicting values), they can likely be safely de-duplicated in data preparation.
  - If duplicates conflict (e.g., different territory_id or other attributes for the same customer_id), this indicates data integration issues or changing attributes over time and requires a clear business rule (e.g., keep latest record, most frequent value, or resolve via additional tables).
- If customer_id has inconsistent formats (multiple lengths / non-UUID patterns):
  - It suggests possible data entry or upstream ETL issues; joining across tables may fail or under-match.

Limitations / issues for modelling
- customer_id is an identifier and MUST NOT be used directly as a predictive feature:
  - It has no causal meaning and can cause models to “memorise” customers (overfitting), leading to unrealistic performance.
- customer_id is essential for joining and aggregation, but it is only useful once we engineer meaningful behavioural features from transactions.

Modelling implications for Student A (classification)
- A clean, unique customer_id enables reliable aggregation from sales_order_header (e.g., orders per customer, days since last order, average order value).
- Ensuring customer_id integrity is a prerequisite for building the classification target (e.g., re-order within next N days) without leakage or incorrect joins.
- For robust evaluation, customer_id should be used to split data appropriately (e.g., time-based split on orders; avoid leakage by ensuring future orders are not used in feature generation).

Ethical / governance note (report-ready)
- customer_id is a pseudonymous identifier; while it is not directly personally identifying on its own, it becomes sensitive when linked to purchase behaviour.
- Data should be handled under privacy-by-design principles: minimisation, secure storage, and limiting outputs to aggregated insights rather than exposing individual-level identifiers.
"""

In [97]:
# Do not modify this code
print_tile(size="h3", key='feature_2_insights', value=feature_2_insights)

### B.4 Explore Feature of Interest `store_id`

In [98]:
# B.4 Feature of Interest: store_id (coverage + usefulness + modelling implications)
feature_3 = "store_id"
print("Selected B.4 feature:", feature_3)

if feature_3 not in df.columns:
    raise ValueError(f"Column '{feature_3}' not found. Available columns: {df.columns.tolist()}")

n = len(df)
missing_cnt = df[feature_3].isna().sum()
missing_pct = round(missing_cnt / n * 100, 2)
present_cnt = n - missing_cnt
present_pct = round(present_cnt / n * 100, 2)

print(f"Rows: {n:,}")
print(f"Missing store_id: {missing_cnt:,} ({missing_pct}%)")
print(f"Present store_id: {present_cnt:,} ({present_pct}%)")

# Uniqueness among non-missing store_id
n_unique_present = df[feature_3].nunique(dropna=True)
print(f"Unique store_id (non-missing): {n_unique_present:,}")

# Distribution of store_id for present values (top stores)
vc = (
    df[feature_3]
    .dropna()
    .astype(str)
    .value_counts()
    .reset_index()
)
vc.columns = [feature_3, "count"]
vc["percent_of_present"] = (vc["count"] / vc["count"].sum() * 100).round(2)
display(vc.head(20))

# Chart: top store_id categories (only present)
top_k = 15
vc_top = vc.head(top_k).copy()

chart = (
    alt.Chart(vc_top)
    .mark_bar()
    .encode(
        x=alt.X("count:Q", title="Count (non-missing only)"),
        y=alt.Y(f"{feature_3}:N", sort="-x", title="store_id (top categories)"),
        tooltip=[feature_3, "count", "percent_of_present"]
    )
    .properties(title=f"Top {top_k} store_id values (non-missing only)", width=700, height=320)
)
chart

Selected B.4 feature: store_id
Rows: 14,275
Missing store_id: 13,823 (96.83%)
Present store_id: 452 (3.17%)
Unique store_id (non-missing): 160

                                store_id  count  percent_of_present
0   af39eeb6-feb3-4df5-a2f1-407ecdc01998      6                1.33
1   f6f5fa00-f44d-439f-88ef-51dfcd15b687      5                1.11
2   d973dcfa-58f0-4659-9305-439cfbabc7cd      5                1.11
3   b4b0f743-12d6-4fff-99ae-b17a7300d04a      5                1.11
4   e0dd80fa-378f-4cd8-916a-bbec07c5a4f2      5                1.11
5   ea5901c7-f681-4276-a3d3-4cc4eee16707      5                1.11
6   34df6cec-bfc2-493a-9260-7304805f11d6      5                1.11
7   0f2a08df-5caf-4b02-956a-ea9a70593ff6      4                0.88
8   beb028c9-6a6a-439f-b36b-77d38792fbc9      4                0.88
9   7f8d6b72-4655-40d7-8498-0897282bfc66      4                0.88
10  c1b41c79-5c63-4783-b2e3-2de1030b01e3      4                0.88
11  96fb6359-e6f4-4eb1-aea2-8d6ea7659391      4                0.88
12  6fb893a6-4949-46c7-87bc-f26a03467d64      4                0.88
13  9d640855-c523-4110-91c3-5223fa422d9b      4                0.88
14  2ef7e76e-6840-46f1-bf6d-f7777fe1eccc      4                0.88
15  e3e91cc4-678c-445a-9b6a-17e085d3d428      4                0.88
16  72b5ea7a-0825-47c4-9017-88f01c86516c      4                0.88
17  540ff070-0090-4ef0-bfe9-4984f69af429      4                0.88
18  0b915398-edde-49ba-a74f-e143556d4c97      4                0.88
19  534b69a0-d8a7-4af2-954e-8e50766f2c90      4                0.88

alt.Chart(...)

In [99]:
# B.4 Extra: store_id missingness by territory_id (bias / coverage risk check)
if "territory_id" in df.columns:
    tmp = df.copy()
    tmp["store_id_missing"] = tmp["store_id"].isna()

    miss_by_terr = (
        tmp.groupby("territory_id")["store_id_missing"]
           .mean()
           .reset_index(name="store_id_missing_rate")
    )
    miss_by_terr["store_id_missing_rate"] = (miss_by_terr["store_id_missing_rate"] * 100).round(2)
    display(miss_by_terr.sort_values("store_id_missing_rate", ascending=False))

    alt.Chart(miss_by_terr).mark_bar().encode(
        x=alt.X("store_id_missing_rate:Q", title="store_id missing rate (%)"),
        y=alt.Y("territory_id:N", sort="-x", title="territory_id"),
        tooltip=["territory_id:N", "store_id_missing_rate:Q"]
    ).properties(title="store_id missingness rate by territory", width=700, height=250)
else:
    print("territory_id not available; cannot compute missingness by territory.")

                           territory_id  store_id_missing_rate
2  2ac923e9-3043-4f5e-bae0-ad28089bf187                  97.90
0  0ad4c625-bb65-4376-8a41-0a65719b0db8                  96.56
3  e0e3bac4-790e-4617-84b3-be0c2bdb7070                  95.98
1  25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2                  95.93

In [100]:
# B.4 Extra 1: Treat missingness as a segment (has_store_id) and compare by territory
df_b4 = df.copy()
df_b4["has_store_id"] = df_b4["store_id"].notna()

seg_summary = (
    df_b4["has_store_id"]
    .value_counts(dropna=False)
    .reset_index()
)
seg_summary.columns = ["has_store_id", "count"]
seg_summary["percent"] = (seg_summary["count"] / seg_summary["count"].sum() * 100).round(2)
display(seg_summary)

if "territory_id" in df_b4.columns:
    terr_seg = (
        df_b4.groupby("territory_id")["has_store_id"]
        .agg(["count", "mean"])
        .reset_index()
        .rename(columns={"count": "n_customers", "mean": "store_id_present_rate"})
    )
    terr_seg["store_id_present_rate"] = (terr_seg["store_id_present_rate"] * 100).round(2)
    display(terr_seg.sort_values("store_id_present_rate", ascending=False))

    alt.Chart(terr_seg).mark_bar().encode(
        x=alt.X("store_id_present_rate:Q", title="store_id present rate (%)"),
        y=alt.Y("territory_id:N", sort="-x", title="territory_id"),
        tooltip=["territory_id:N", "n_customers:Q", "store_id_present_rate:Q"]
    ).properties(title="store_id present rate by territory (missing-not-at-random check)", width=700, height=250)
else:
    print("territory_id not available; skipping by-territory analysis.")

   has_store_id  count  percent
0         False  13823    96.83
1          True    452     3.17

                           territory_id  n_customers  store_id_present_rate
1  25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2         2851                   4.07
3  e0e3bac4-790e-4617-84b3-be0c2bdb7070         3008                   4.02
0  0ad4c625-bb65-4376-8a41-0a65719b0db8         2849                   3.44
2  2ac923e9-3043-4f5e-bae0-ad28089bf187         5567                   2.10

In [101]:
# B.4 Extra 2: Concentration analysis on non-missing store_id values
non_missing = df["store_id"].dropna().astype(str)

if len(non_missing) == 0:
    print("No non-missing store_id values to analyse.")
else:
    vc = non_missing.value_counts().reset_index()
    vc.columns = ["store_id", "count"]
    vc["percent_of_present"] = (vc["count"] / vc["count"].sum() * 100).round(2)
    vc["cum_percent"] = vc["percent_of_present"].cumsum().round(2)
    display(vc.head(30))

    # How many stores cover 80% of present records?
    n_80 = int((vc["cum_percent"] <= 80).sum() + 1) if (vc["cum_percent"] <= 80).any() else 1
    print(f"Stores needed to cover ~80% of non-missing records: {n_80}")

    # Pareto-like chart (top 20)
    top = vc.head(20).copy()
    bars = alt.Chart(top).mark_bar().encode(
        x=alt.X("store_id:N", sort="-y", title="store_id (top 20)"),
        y=alt.Y("percent_of_present:Q", title="% of non-missing subset"),
        tooltip=["store_id:N", "count:Q", "percent_of_present:Q", "cum_percent:Q"]
    ).properties(width=700, height=260, title="store_id concentration (top 20 stores)")

    line = alt.Chart(top).mark_line(color="black").encode(
        x=alt.X("store_id:N", sort="-y"),
        y=alt.Y("cum_percent:Q", title="Cumulative %")
    )

    (bars + line).resolve_scale(y="independent")

,store_id,count,percent_of_present,cum_percent
0,af39eeb6-feb3-4df5-a2f1-407ecdc01998,6,1.33,1.33
1,f6f5fa00-f44d-439f-88ef-51dfcd15b687,5,1.11,2.44
2,d973dcfa-58f0-4659-9305-439cfbabc7cd,5,1.11,3.55
3,b4b0f743-12d6-4fff-99ae-b17a7300d04a,5,1.11,4.66
4,e0dd80fa-378f-4cd8-916a-bbec07c5a4f2,5,1.11,5.77
5,ea5901c7-f681-4276-a3d3-4cc4eee16707,5,1.11,6.88
6,34df6cec-bfc2-493a-9260-7304805f11d6,5,1.11,7.99
7,0f2a08df-5caf-4b02-956a-ea9a70593ff6,4,0.88,8.87
8,beb028c9-6a6a-439f-b36b-77d38792fbc9,4,0.88,9.75
9,7f8d6b72-4655-40d7-8498-0897282bfc66,4,0.88,10.63
10,c1b41c79-5c63-4783-b2e3-2de1030b01e3,4,0.88,11.51
11,96fb6359-e6f4-4eb1-aea2-8d6ea7659391,4,0.88,12.39
12,6fb893a6-4949-46c7-87bc-f26a03467d64,4,0.88,13.27
13,9d640855-c523-4110-91c3-5223fa422d9b,4,0.88,14.15
14,2ef7e76e-6840-46f1-bf6d-f7777fe1eccc,4,0.88,15.03
15,e3e91cc4-678c-445a-9b6a-17e085d3d428,4,0.88,15.91
16,72b5ea7a-0825-47c4-9017-88f01c86516c,4,0.88,16.79
17,540ff070-0090-4ef0-bfe9-4984f69af429,4,0.88,17.67
18,0b915398-edde-49ba-a74f-e143556d4c97,4,0.88,18.55
19,534b69a0-d8a7-4af2-954e-8e50766f2c90,4,0.88,19.43
20,48b871f6-4261-4ae1-9e66-f8cb509f6e03,4,0.88,20.31
21,ec670213-d910-4f47-83e0-aa41d239e11e,4,0.88,21.19
22,dcef1c30-86b7-4895-997b-91ff416df130,4,0.88,22.07
23,855a575f-9e21-4e6a-952f-2c0023e82558,4,0.88,22.95
24,196398f5-35dc-451e-87dd-c051b8539381,4,0.88,23.83
25,a843d8a6-f0ed-47f2-a051-21408da51910,4,0.88,24.71
26,776ce631-8229-4b50-a857-c6a48d8e5716,4,0.88,25.59
27,0a7f5f12-801e-49d7-8a1f-7a6954ac9e04,4,0.88,26.47
28,3f7e8c9d-6305-468a-86f2-9258bca9c269,4,0.88,27.35
29,874113ca-03bf-40e6-b1e5-cb118681af01,4,0.88,28.23

Stores needed to cover ~80% of non-missing records: 109

In [102]:
# B.4 Extra 3: Consistency - does a customer_id map to multiple store_id values?
if "customer_id" in df.columns:
    store_per_customer = df.groupby("customer_id")["store_id"].nunique(dropna=False)
    n_multi = int((store_per_customer > 1).sum())
    print(f"Customers with >1 store_id (including missing as a value): {n_multi:,}")

    if n_multi > 0:
        bad_ids = store_per_customer[store_per_customer > 1].index[:10].tolist()
        display(df[df["customer_id"].isin(bad_ids)][["customer_id", "store_id", "territory_id"]].sort_values("customer_id").head(50))
else:
    print("customer_id not found; skipping customer->store mapping check.")

Customers with >1 store_id (including missing as a value): 0

In [104]:
# B.4 Extra 4: Compare key categorical attributes between has_store_id segments
df_seg = df.copy()

# Create segment flag ONCE (and overwrite safely if it already exists)
df_seg["has_store_id"] = df_seg["store_id"].notna()

# Pick a few categorical columns to compare (exclude IDs + store_id itself)
cat_cols = df_seg.select_dtypes(include=["object", "category", "bool"]).columns.tolist()
exclude = {"customer_id", "store_id", "account_number"}  # keep territory_id for comparison if present
candidate_cats = [c for c in cat_cols if c not in exclude and c != "has_store_id"]

print("Candidate categorical columns for segment comparison:", candidate_cats[:20])

# Always compare territory_id if available
cols_to_compare = []
if "territory_id" in df_seg.columns:
    cols_to_compare.append("territory_id")

# Add up to 2 more moderate-cardinality columns (2..30 unique)
for c in candidate_cats:
    nun = df_seg[c].nunique(dropna=True)
    if 2 <= nun <= 30 and c not in cols_to_compare:
        cols_to_compare.append(c)
    if len(cols_to_compare) >= 3:
        break

print("Comparing columns:", cols_to_compare)

for c in cols_to_compare:
    # Build a minimal temp df to avoid column collisions
    tmp_df = df_seg[["has_store_id", c]].copy()
    tmp_df[c] = tmp_df[c].fillna("<<MISSING>>").astype(str)

    tmp = (
        tmp_df.groupby(["has_store_id", c], as_index=False)
              .size()
              .rename(columns={"size": "count"})
    )

    # percentage within each segment
    tmp["segment_total"] = tmp.groupby("has_store_id")["count"].transform("sum")
    tmp["percent_within_segment"] = (tmp["count"] / tmp["segment_total"] * 100).round(2)

    display(tmp.sort_values(["has_store_id", "percent_within_segment"], ascending=[True, False]).head(30))

    chart = (
        alt.Chart(tmp)
        .mark_bar()
        .encode(
            x=alt.X("percent_within_segment:Q", title="Percent within segment (%)"),
            y=alt.Y(f"{c}:N", sort="-x", title=c),
            color=alt.Color("has_store_id:N", title="Has store_id?"),
            tooltip=[
                alt.Tooltip("has_store_id:N", title="has_store_id"),
                alt.Tooltip(f"{c}:N", title=c),
                alt.Tooltip("count:Q", title="count"),
                alt.Tooltip("percent_within_segment:Q", title="% within segment")
            ],
        )
        .properties(title=f"{c} distribution by store_id availability", width=700, height=260)
    )

    display(chart)

Candidate categorical columns for segment comparison: ['person_id', 'territory_id']
Comparing columns: ['territory_id']

,has_store_id,territory_id,count,segment_total,percent_within_segment
2,False,2ac923e9-3043-4f5e-bae0-ad28089bf187,5450,13823,39.43
3,False,e0e3bac4-790e-4617-84b3-be0c2bdb7070,2887,13823,20.89
0,False,0ad4c625-bb65-4376-8a41-0a65719b0db8,2751,13823,19.90
1,False,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,2735,13823,19.79
7,True,e0e3bac4-790e-4617-84b3-be0c2bdb7070,121,452,26.77
6,True,2ac923e9-3043-4f5e-bae0-ad28089bf187,117,452,25.88
5,True,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,116,452,25.66
4,True,0ad4c625-bb65-4376-8a41-0a65719b0db8,98,452,21.68

alt.Chart(...)

In [105]:
# B.4 Extra 5: Modelling decision table for store_id
decision = []

missing_pct = df["store_id"].isna().mean() * 100
n_unique = df["store_id"].nunique(dropna=True)
decision.append({
    "feature": "store_id",
    "missing_%": round(missing_pct, 2),
    "n_unique_non_missing": int(n_unique),
    "risk": "Very high missingness; potential MNAR; may bias model",
    "recommended_handling": "Prefer exclude from final model OR use has_store_id flag + 'Unknown' category; group rare stores",
    "reason": "Feature may only exist for a specific customer segment; treat presence as informative"
})

decision_df = pd.DataFrame(decision)
display(decision_df)

,feature,missing_%,n_unique_non_missing,risk,recommended_handling,reason
0,store_id,96.83,160,Very high missingness; potential MNAR; may bia...,Prefer exclude from final model OR use has_sto...,Feature may only exist for a specific customer...

In [106]:
# <Student to fill this section>
feature_n_insights = """
Feature explored (B.4): store_id (store linkage / channel proxy) and store_id availability segment (has_store_id)

Why this feature matters (business + modelling relevance)
- store_id is intended to link customers to the store dataset (store.csv), enabling store-level context such as store type, location, and potentially channel (in-store vs not linked to a store).
- For Student A’s classification use case (e.g., predicting whether a customer will re-order), store context can be predictive because purchasing behaviour may differ by store catchment area, customer demographics, and local promotions.

Distribution & coverage (key EDA finding)
- store_id has extremely high missingness (~96–97% missing in the customer table, based on the missingness analysis).
- This means only a small subset of customers can be enriched with store-level attributes via joins.
- Among the non-missing subset, store_id values can be analysed as a categorical distribution (top stores), and the concentration check (Pareto-style) indicates whether a few stores dominate the observed subset.

What the missingness likely implies (missing-not-at-random risk)
- The missingness of store_id is unlikely to be random. Plausible explanations include:
  - customers who primarily purchase online or via channels not associated with a store,
  - incomplete customer-store linkage in the retailer’s systems,
  - historical records lacking store linkage while newer records include it.
- Because store_id presence may correlate with customer segment and behaviour, using store_id naively can introduce bias and reduce generalisability.

Quality and consistency checks performed
- Coverage: computed missing count and missing rate for store_id.
- Cardinality: counted unique store_id values among non-missing rows to assess encoding complexity.
- Segment comparison: created has_store_id (True/False) and compared its rate across territory_id and other categorical attributes to test whether store_id availability is concentrated in specific territories/segments.
- Mapping consistency (optional): if customer_id duplicates exist, checked whether a customer maps to multiple store_id values (potential data integration issue).

How to handle in preparation/model training (recommendation)
- store_id should primarily be treated as a join key rather than a direct predictor.
- Because of the high missingness:
  - create a binary feature has_store_id (presence/absence) which can itself be informative,
  - if using store_id as a categorical predictor, include an explicit 'Unknown' level for missing values and group rare stores to reduce noise,
  - evaluate model performance separately for customers with store_id present vs missing to ensure the model is reliable and fair across segments.
- If store_id does not improve validation performance (especially on a time-based split), it should be excluded from the final model to avoid overfitting to a non-representative subset.

Business impact & ethical considerations (report-ready)
- If store_id availability aligns with a particular customer channel/segment, actions driven by the model (e.g., retention offers) could inadvertently favour customers from linked stores and under-serve customers without store linkage.
- The recommended approach is to treat store_id missingness as a segment feature and to monitor performance and targeting outcomes across territories and store-linked vs non-store-linked customers.
"""

In [107]:
# Do not modify this code
print_tile(size="h3", key='feature_n_insights', value=feature_n_insights)

In [108]:
# Cross-feature comparison: territory_id (B2) vs customer_id (B3) vs store_id (B4)

features = ["territory_id", "customer_id", "store_id"]
rows = []

for f in features:
    if f not in df.columns:
        continue

    s = df[f]
    rows.append({
        "feature": f,
        "dtype": str(s.dtype),
        "missing_%": round(s.isna().mean() * 100, 2),
        "n_unique_non_missing": int(s.nunique(dropna=True)),
        "duplicated_values": int(s.duplicated().sum()) if f == "customer_id" else None,
        "example_top_value": str(s.dropna().astype(str).value_counts().index[0]) if s.notna().any() else None,
        "top_value_%": round((s.dropna().astype(str).value_counts(normalize=True).iloc[0] * 100), 2) if s.notna().any() else None,
    })

compare_df = pd.DataFrame(rows)
display(compare_df)

,feature,dtype,missing_%,n_unique_non_missing,duplicated_values,example_top_value,top_value_%
0,territory_id,object,0.00,4,NaN,2ac923e9-3043-4f5e-bae0-ad28089bf187,39.00
1,customer_id,object,0.00,10331,3944.0,874949cb-8236-4956-87e6-99e9bfa58ce7,0.02
2,store_id,object,96.83,160,NaN,af39eeb6-feb3-4df5-a2f1-407ecdc01998,1.33

In [110]:
# B.5 Cross-feature comparison: territory_id (B2) vs customer_id (B3) vs store_id (B4)

compare_features = ["territory_id", "customer_id", "store_id"]
compare_features = [f for f in compare_features if f in df.columns]

rows = []
for f in compare_features:
    s = df[f]

    # Basic stats
    missing_pct = round(s.isna().mean() * 100, 2)
    n_unique = int(s.nunique(dropna=True))
    dtype = str(s.dtype)

    # Top category concentration (if non-missing exists)
    top_val = None
    top_val_pct = None
    if s.notna().any():
        vc = s.dropna().astype(str).value_counts(normalize=True)
        top_val = str(vc.index[0])
        top_val_pct = round(float(vc.iloc[0] * 100), 2)

    # Duplicates only meaningful for customer_id (join key integrity)
    dup_vals = None
    if f == "customer_id":
        dup_vals = int(s.duplicated().sum())

    rows.append({
        "feature": f,
        "dtype": dtype,
        "missing_%": missing_pct,
        "n_unique_non_missing": n_unique,
        "top_value_%": top_val_pct,
        "duplicate_values_(only_customer_id)": dup_vals,
    })

compare_df = pd.DataFrame(rows)
display(compare_df)

,feature,dtype,missing_%,n_unique_non_missing,top_value_%,duplicate_values_(only_customer_id)
0,territory_id,object,0.00,4,39.00,NaN
1,customer_id,object,0.00,10331,0.02,3944.0
2,store_id,object,96.83,160,1.33,NaN

In [113]:
# Visual comparison of missingness rates
miss_comp = compare_df[["feature", "missing_%"]].copy()

alt.Chart(miss_comp).mark_bar().encode(
    x=alt.X("missing_%:Q", title="Missing values (%)"),
    y=alt.Y("feature:N", sort="-x", title="Feature"),
    tooltip=["feature:N", "missing_%:Q"]
).properties(title="Missingness comparison: territory_id vs customer_id vs store_id", width=650, height=200)

alt.Chart(...)

In [112]:
card_comp = compare_df[["feature", "n_unique_non_missing"]].copy()

alt.Chart(card_comp).mark_bar().encode(
    x=alt.X("n_unique_non_missing:Q", title="Unique values (non-missing)"),
    y=alt.Y("feature:N", sort="-x", title="Feature"),
    tooltip=["feature:N", "n_unique_non_missing:Q"]
).properties(
    title="Cardinality comparison (B2 vs B3 vs B4)",
    width=650,
    height=200
)

alt.Chart(...)

In [114]:
# Auto-generate a report-ready comparison summary
def row_for(feature):
    return compare_df.loc[compare_df["feature"] == feature].iloc[0].to_dict() if feature in compare_df["feature"].values else None

r_terr = row_for("territory_id")
r_cust = row_for("customer_id")
r_store = row_for("store_id")

summary_lines = []

if r_terr:
    summary_lines.append(
        f"- territory_id (B.2) is a clean, low-cardinality categorical feature "
        f"({r_terr['n_unique_non_missing']} unique values) with {r_terr['missing_%']}% missingness. "
        f"It is a strong candidate predictor and also supports fairness/performance checks by territory."
    )

if r_cust:
    dup = r_cust["duplicate_values_(only_customer_id)"]
    summary_lines.append(
        f"- customer_id (B.3) is a join key, not a predictor. It has {r_cust['missing_%']}% missingness "
        f"and {r_cust['n_unique_non_missing']} unique IDs. "
        f"Duplicate customer_id values (data integrity risk for joins/aggregation): {dup if dup is not None else 'N/A'}."
    )

if r_store:
    summary_lines.append(
        f"- store_id (B.4) has very high missingness ({r_store['missing_%']}%), meaning store enrichment applies only "
        f"to a small subset of customers. Because missingness is likely not random, store_id should be handled carefully "
        f"(e.g., use has_store_id flag and an 'Unknown' category) and may be excluded from the final model unless it improves "
        f"validation performance without introducing bias."
    )

cross_feature_summary = "\n".join(summary_lines)
print(cross_feature_summary)

- territory_id (B.2) is a clean, low-cardinality categorical feature (4 unique values) with 0.0% missingness. It is a strong candidate predictor and also supports fairness/performance checks by territory.
- customer_id (B.3) is a join key, not a predictor. It has 0.0% missingness and 10331 unique IDs. Duplicate customer_id values (data integrity risk for joins/aggregation): 3944.0.
- store_id (B.4) has very high missingness (96.83%), meaning store enrichment applies only to a small subset of customers. Because missingness is likely not random, store_id should be handled carefully (e.g., use has_store_id flag and an 'Unknown' category) and may be excluded from the final model unless it improves validation performance without introducing bias.

In [116]:
import textwrap

print("\n" + "="*80)
print("Cross-feature comparison summary (B.2 vs B.3 vs B.4)")
print("="*80)

for i, line in enumerate(summary_lines, start=1):
    wrapped = textwrap.fill(line, width=90, subsequent_indent="   ")
    print(f"{i}. {wrapped}\n")

================================================================================
Cross-feature comparison summary (B.2 vs B.3 vs B.4)
================================================================================
1. - territory_id (B.2) is a clean, low-cardinality categorical feature (4 unique values)
   with 0.0% missingness. It is a strong candidate predictor and also supports
   fairness/performance checks by territory.

2. - customer_id (B.3) is a join key, not a predictor. It has 0.0% missingness and 10331
   unique IDs. Duplicate customer_id values (data integrity risk for joins/aggregation):
   3944.0.

3. - store_id (B.4) has very high missingness (96.83%), meaning store enrichment applies only
   to a small subset of customers. Because missingness is likely not random, store_id
   should be handled carefully (e.g., use has_store_id flag and an 'Unknown' category) and
   may be excluded from the final model unless it improves validation performance without
   introducing bias.