# **EDA Notebook**

---
## 0. Setup Environment

In [1]:
# DO NOT MODIFY THE CODE IN THIS CELL
!pip install -q utstd

from utstd.folders import *
from utstd.ipyrenders import *

at = AtFolder(
    course_code=36106,
    assignment="AT3",
)
at.run()

import warnings
warnings.simplefilter(action='ignore')

WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
    WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
    WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
    WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)

You can now save your data files in: /Users/aryan/Machine Learning Assignment 3/36106/assignment/AT3/data

WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
utstd 0.1.8 requires scikit-learn~=1.5.1, but you have scikit-learn 1.6.1 which is incompatible.
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/Users/aryan/.venvs/dbt311/lib/python3.11/site-packages)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
sh: import: command not found
sh: -c: line 0: syntax error near unexpected token `"ignore"'
sh: -c: line 0: `warnings.filterwarnings("ignore")'

---
## Student Information

In [2]:
# <Student to fill this section>
group_name = "36106-26AU-AT3-Group01"
student_name = "Aryan Goel"
student_id = "26040826"

In [3]:
# Do not modify this code
print_tile(size="h1", key='group_name', value=group_name)

In [4]:
# Do not modify this code
print_tile(size="h1", key='student_name', value=student_name)

In [5]:
# Do not modify this code
print_tile(size="h1", key='student_id', value=student_id)

---
## 0. Python Packages

### 0.a Install Additional Packages

> If you are using additional packages, you need to install them here using the command: `! pip install <package_name>`

In [6]:
# <Student to fill this section>

### 0.b Import Packages

In [7]:
# <Student to fill this section>
import pandas as pd
import altair as alt

---
## B. Data Understanding

In [8]:
# Do not modify this code
try:
  df = pd.read_csv(at.folder_path / "unit_measure.csv")
except Exception as e:
  print(e)

### B.1 Explore Dataset

In [9]:
# <Student to fill this section>
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)

print("Shape:", df.shape)
display(df.head(10))

# Schema + missingness + uniqueness profile
profile = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "non_null": df.notna().sum().values,
    "nulls": df.isna().sum().values,
    "null_%": (df.isna().mean() * 100).round(2).values,
    "n_unique": [df[c].nunique(dropna=True) for c in df.columns],
}).sort_values(["null_%", "n_unique"], ascending=[False, False])

display(profile)

# Duplicate row check
dup_rows = int(df.duplicated().sum())
print(f"Duplicate rows: {dup_rows:,} ({dup_rows/len(df)*100:.2f}%)" if len(df) else "Duplicate rows: N/A (empty df)")

# Identify likely key columns
id_cols = [c for c in df.columns if c.lower().endswith("id")]
code_cols = [c for c in df.columns if "code" in c.lower() or "abbr" in c.lower()]
name_cols = [c for c in df.columns if "name" in c.lower() or "description" in c.lower()]

print("ID-like columns:", id_cols)
print("Code/abbrev-like columns:", code_cols)
print("Name/description-like columns:", name_cols)

# Check uniqueness of the likely primary key
pk = id_cols[0] if len(id_cols) else None
if pk:
    print(f"Primary key candidate: {pk}")
    print(" - missing %:", round(df[pk].isna().mean() * 100, 4))
    print(" - duplicates:", int(df[pk].duplicated().sum()))
    print(" - n_unique:", int(df[pk].nunique(dropna=True)))

# Quick value counts for small categorical columns
for c in code_cols + name_cols:
    if c in df.columns and df[c].nunique(dropna=False) <= 50:
        vc = df[c].fillna("<<MISSING>>").astype(str).value_counts().reset_index()
        vc.columns = [c, "count"]
        display(vc)

Shape: (38, 2)

                      unit_measure_code               name
0  ee0468c7-6417-489a-b233-da57ab966174              Boxes
1  7768b253-7430-402f-b90f-1e025c57459b             Bottle
2  1f485b4e-fc4d-47b2-ab57-af19b21eee40            Celsius
3  e87c6cb9-24ca-405a-996c-8f59ab7730fa           Canister
4  91fa7aa6-72aa-40a6-822f-8b80aa9f6376             Carton
5  1f5f8ee7-58c4-4c4e-b8db-b7c1025b3400       Cubic meters
6  b4c6422a-e170-4911-852f-38a7c19f5573   Cubic centimeter
7  5c3d2f68-8573-4e53-8c4e-a72a5f92518e    Cubic decimeter
8  e2e52698-ce31-4fb2-866f-bcffbdfd3147         Centimeter
9  7d2f574f-2c4b-45e5-bb2e-7c74c247492c  Square centimeter

              column   dtype  non_null  nulls  null_%  n_unique
0  unit_measure_code  object        38      0     0.0        38
1               name  object        38      0     0.0        38

Duplicate rows: 0 (0.00%)
ID-like columns: []
Code/abbrev-like columns: ['unit_measure_code']
Name/description-like columns: ['name']

                       unit_measure_code  count
0   ee0468c7-6417-489a-b233-da57ab966174      1
1   8cb5f9fe-f273-42f3-96e4-1f93e26bb318      1
2   d8954392-48a0-4cce-af48-15a83ab47274      1
3   ee700422-0d9b-48c5-ae33-d08b8b5034bf      1
4   57ee0c60-3085-4d9c-bae2-26022aa2d447      1
5   aea9d8c5-cf48-46e0-afa3-f36c6cf44c4e      1
6   c4797df8-be0b-4d3a-a6c4-0f1765f0a822      1
7   dd058911-cfcb-4c19-9df7-a8f40bbccf13      1
8   ee1d7851-244e-47db-8960-bced186cccad      1
9   b0a224d6-adce-4062-b701-32d569ddaa05      1
10  7768b253-7430-402f-b90f-1e025c57459b      1
11  3fbce844-926c-442f-87d9-9017094ed6b7      1
12  1316d404-c512-49da-bfb6-f6df816570ef      1
13  5c50e872-03a3-4aa1-8d0a-103cdf0fc00d      1
14  6ad6e4b7-e1c2-42f2-90f6-306f08b41623      1
15  2eb286e8-8050-4cf5-a260-fd2cedb6e1f4      1
16  5885bdb8-189e-4001-9f96-9cffd780b130      1
17  14266c5d-bb1d-4b58-9d8d-f13f6eb35863      1
18  8dae8c54-6149-48bd-a0e1-9050f4ee82b6      1
19  7cca3216-2076-4b76-b746-8d4a33c94222      1
20  acbdd92d-1e1f-4ba8-a695-3f0c82d87759      1
21  8c4f020f-f9c1-492b-8395-1372b7bda7a7      1
22  1f485b4e-fc4d-47b2-ab57-af19b21eee40      1
23  e87c6cb9-24ca-405a-996c-8f59ab7730fa      1
24  91fa7aa6-72aa-40a6-822f-8b80aa9f6376      1
25  1f5f8ee7-58c4-4c4e-b8db-b7c1025b3400      1
26  b4c6422a-e170-4911-852f-38a7c19f5573      1
27  5c3d2f68-8573-4e53-8c4e-a72a5f92518e      1
28  e2e52698-ce31-4fb2-866f-bcffbdfd3147      1
29  7d2f574f-2c4b-45e5-bb2e-7c74c247492c      1
30  44f61043-62cb-4dea-a921-edf1df4b6a39      1
31  609a70c5-01f5-48f0-9939-4f04449e2018      1
32  0cc915c9-7473-4676-afff-2a4d4f023594      1
33  28bd7d2e-b75a-40dc-b62f-f360a9de2559      1
34  75fa117b-bb26-4752-8ec5-771acf4c50f6      1
35  8dbf3502-309f-4636-9f3e-1ae1cabc748b      1
36  cf068cf8-e6f9-4956-b31b-1d6eb91f3c5c      1
37  a24c076e-f88e-44e9-811b-b4a3da40d463      1

                    name  count
0                  Boxes      1
1            Cubic meter      1
2   Kilogram/cubic meter      1
3              Kilometer      1
4                Kiloton      1
5                  Liter      1
6               US pound      1
7                  Meter      1
8           Square meter      1
9              Milligram      1
10                Bottle      1
11            Milliliter      1
12            Millimeter      1
13                Ounces      1
14                  Pack      1
15                Pallet      1
16                 Piece      1
17            Percentage      1
18              Kilogram      1
19                  Inch      1
20                Gallon      1
21                  Gram      1
22               Celsius      1
23              Canister      1
24                Carton      1
25          Cubic meters      1
26      Cubic centimeter      1
27       Cubic decimeter      1
28            Centimeter      1
29     Square centimeter      1
30                 Crate      1
31                  Case      1
32             Container      1
33             Decimeter      1
34                 Dozen      1
35                  Each      1
36            Cubic foot      1
37       Pint, US liquid      1

In [10]:
# B.1 Extra: consistency checks (whitespace/case) + potential duplicates by code/name
df_clean = df.copy()

# Trim string columns
str_cols = df_clean.select_dtypes(include=["object", "string"]).columns.tolist()
for c in str_cols:
    df_clean[c] = df_clean[c].astype(str).str.strip()

print("String columns trimmed:", str_cols)

# Detect potential duplicates ignoring case (common dimension-table issue)
for c in str_cols:
    lowered = df_clean[c].str.lower()
    dup_case_insensitive = lowered.duplicated().sum()
    if dup_case_insensitive > 0:
        print(f"Potential case-insensitive duplicates in '{c}':", int(dup_case_insensitive))
        display(df_clean.loc[lowered.duplicated(keep=False), [c]].sort_values(c).head(50))

String columns trimmed: ['unit_measure_code', 'name']

In [11]:
# === INSERT AFTER CELL 16 ===
# B.1 Extra: Missingness bar chart
missing = (df.isna().mean() * 100).round(2).reset_index()
missing.columns = ["column", "missing_pct"]

alt.Chart(missing).mark_bar().encode(
    x=alt.X("missing_pct:Q", title="Missing %", scale=alt.Scale(domain=[0, 100])),
    y=alt.Y("column:N", sort="-x", title="Column"),
    tooltip=["column:N", "missing_pct:Q"],
).properties(
    title="unit_measure: Missing values by column",
    width=400, height=150,
)

alt.Chart(...)

In [12]:
df.isna().sum().sort_values(ascending=False)

unit_measure_code    0
name                 0
dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   unit_measure_code  38 non-null     object
 1   name               38 non-null     object
dtypes: object(2)
memory usage: 740.0+ bytes

In [14]:
# <Student to fill this section>
dataset_insights = f"""
unit_measure dataset overview (unit_measure.csv)

1) Dataset role (dimension/lookup table)
- This table is a reference (dimension) dataset that defines measurement units used elsewhere in the database.
- It typically supports joins from fact tables (e.g., product or order detail tables) via a unit_measure_id and provides human-readable unit codes/names.

2) Grain and keys
- Expected grain: 1 row per unit of measure.
- A unit_measure_id (or similar ID field) should be unique and non-null to ensure reliable joins and prevent duplicate matches.

3) Size and structure
- The dataset contains {df.shape[0]:,} rows and {df.shape[1]:,} columns.
- We inspected schema (dtypes), missingness, unique counts, and duplicates to confirm it behaves like a clean reference table.

4) Data quality checks performed
- Completeness checks: measured missingness across columns (IDs, unit code/abbreviation, unit name).
- Uniqueness checks: validated that the primary key candidate has no duplicates and minimal missingness.
- Naming consistency checks: assessed whether unit codes/names contain whitespace/case inconsistencies that could create accidental duplicates.
- Duplicate row checks: ensured there are no repeated reference records.

5) Modelling relevance (Student A)
- unit_measure is not a predictive feature by itself; its main value is enabling correct interpretation of quantities (e.g., weights, lengths) and consistent feature engineering if quantities are used later.
- Ensuring join integrity here prevents downstream errors where product quantities might be incorrectly interpreted due to missing or duplicated unit definitions.

Conclusion
- A clean and unique unit_measure dimension improves data integrity across the wider pipeline by ensuring consistent measurement metadata during joins.
"""

In [15]:
# Do not modify this code
print_tile(size="h3", key='dataset_insights', value=dataset_insights)

### B.2 Explore Feature of Interest `unit_measure_code`

In [16]:
# <Student to fill this section>
# B.2: Explore a "code/abbreviation" feature (best for unit_measure tables)
code_candidates = [c for c in df.columns if "code" in c.lower() or "abbr" in c.lower()]
feature_1 = code_candidates[0] if len(code_candidates) else None
print("Selected feature_1:", feature_1)

if feature_1:
    vc = df[feature_1].fillna("<<MISSING>>").astype(str).value_counts().reset_index()
    vc.columns = [feature_1, "count"]
    vc["percent"] = (vc["count"] / vc["count"].sum() * 100).round(2)
    display(vc)

    alt.Chart(vc).mark_bar().encode(
        x=alt.X("count:Q", title="Count"),
        y=alt.Y(f"{feature_1}:N", sort="-x", title=feature_1),
        tooltip=[feature_1, "count", "percent"]
    ).properties(
        title=f"Distribution of {feature_1}",
        width=700,
        height=max(180, min(500, 20 * len(vc)))
    )
else:
    print("No code/abbreviation column found; check df.columns.")

Selected feature_1: unit_measure_code

                       unit_measure_code  count  percent
0   ee0468c7-6417-489a-b233-da57ab966174      1     2.63
1   8cb5f9fe-f273-42f3-96e4-1f93e26bb318      1     2.63
2   d8954392-48a0-4cce-af48-15a83ab47274      1     2.63
3   ee700422-0d9b-48c5-ae33-d08b8b5034bf      1     2.63
4   57ee0c60-3085-4d9c-bae2-26022aa2d447      1     2.63
5   aea9d8c5-cf48-46e0-afa3-f36c6cf44c4e      1     2.63
6   c4797df8-be0b-4d3a-a6c4-0f1765f0a822      1     2.63
7   dd058911-cfcb-4c19-9df7-a8f40bbccf13      1     2.63
8   ee1d7851-244e-47db-8960-bced186cccad      1     2.63
9   b0a224d6-adce-4062-b701-32d569ddaa05      1     2.63
10  7768b253-7430-402f-b90f-1e025c57459b      1     2.63
11  3fbce844-926c-442f-87d9-9017094ed6b7      1     2.63
12  1316d404-c512-49da-bfb6-f6df816570ef      1     2.63
13  5c50e872-03a3-4aa1-8d0a-103cdf0fc00d      1     2.63
14  6ad6e4b7-e1c2-42f2-90f6-306f08b41623      1     2.63
15  2eb286e8-8050-4cf5-a260-fd2cedb6e1f4      1     2.63
16  5885bdb8-189e-4001-9f96-9cffd780b130      1     2.63
17  14266c5d-bb1d-4b58-9d8d-f13f6eb35863      1     2.63
18  8dae8c54-6149-48bd-a0e1-9050f4ee82b6      1     2.63
19  7cca3216-2076-4b76-b746-8d4a33c94222      1     2.63
20  acbdd92d-1e1f-4ba8-a695-3f0c82d87759      1     2.63
21  8c4f020f-f9c1-492b-8395-1372b7bda7a7      1     2.63
22  1f485b4e-fc4d-47b2-ab57-af19b21eee40      1     2.63
23  e87c6cb9-24ca-405a-996c-8f59ab7730fa      1     2.63
24  91fa7aa6-72aa-40a6-822f-8b80aa9f6376      1     2.63
25  1f5f8ee7-58c4-4c4e-b8db-b7c1025b3400      1     2.63
26  b4c6422a-e170-4911-852f-38a7c19f5573      1     2.63
27  5c3d2f68-8573-4e53-8c4e-a72a5f92518e      1     2.63
28  e2e52698-ce31-4fb2-866f-bcffbdfd3147      1     2.63
29  7d2f574f-2c4b-45e5-bb2e-7c74c247492c      1     2.63
30  44f61043-62cb-4dea-a921-edf1df4b6a39      1     2.63
31  609a70c5-01f5-48f0-9939-4f04449e2018      1     2.63
32  0cc915c9-7473-4676-afff-2a4d4f023594      1     2.63
33  28bd7d2e-b75a-40dc-b62f-f360a9de2559      1     2.63
34  75fa117b-bb26-4752-8ec5-771acf4c50f6      1     2.63
35  8dbf3502-309f-4636-9f3e-1ae1cabc748b      1     2.63
36  cf068cf8-e6f9-4956-b31b-1d6eb91f3c5c      1     2.63
37  a24c076e-f88e-44e9-811b-b4a3da40d463      1     2.63

In [17]:
# <Student to fill this section>
# B.2 Explore Feature of Interest: UnitMeasureCode (or abbreviation/code)

# 1) Choose the best "code" column (priority-based)
priority_code_cols = [
    "unit_measure_code", "unitmeasurecode", "unit_code", "uom_code", "code",
    "abbreviation", "abbr", "uom"
]

feature_1 = next((c for c in priority_code_cols if c in df.columns), None)

# Fallback: any column containing code/abbr/uom
if feature_1 is None:
    code_candidates = [c for c in df.columns if any(k in c.lower() for k in ["code", "abbr", "uom"])]
    feature_1 = code_candidates[0] if len(code_candidates) else None

print("Selected feature_1 (unit code):", feature_1)

if feature_1:
    # 2) Basic profiling
    s = df[feature_1]
    summary = pd.DataFrame([{
        "feature": feature_1,
        "rows": len(df),
        "missing_count": int(s.isna().sum()),
        "missing_%": round(s.isna().mean() * 100, 2),
        "n_unique_non_missing": int(s.nunique(dropna=True)),
        "duplicate_count": int(s.dropna().astype(str).duplicated().sum()),
    }])
    display(summary)

    # 3) Cleaned version for consistency checks
    clean = s.fillna("<<MISSING>>").astype(str).str.strip()
    clean_lower = clean.str.lower()

    # Case/whitespace inconsistencies (e.g., "KG" vs "kg", "kg " vs "kg")
    inconsistent = pd.DataFrame({
        "raw": clean,
        "clean_lower": clean_lower
    })

    # Groups where same clean_lower maps to multiple raw representations
    reps = (inconsistent.groupby("clean_lower")["raw"].nunique().reset_index(name="n_raw_variants")
            .sort_values("n_raw_variants", ascending=False))
    reps = reps[reps["n_raw_variants"] > 1]
    print("Potential case/whitespace inconsistencies (same code, multiple raw variants):", len(reps))
    if len(reps) > 0:
        display(reps.head(20))

    # 4) Value counts table
    vc = clean.value_counts().reset_index()
    vc.columns = [feature_1, "count"]
    vc["percent"] = (vc["count"] / vc["count"].sum() * 100).round(2)
    display(vc)

    # 5) Chart (good for small dimension tables)
    alt.Chart(vc).mark_bar().encode(
        x=alt.X("count:Q", title="Count"),
        y=alt.Y(f"{feature_1}:N", sort="-x", title=feature_1),
        tooltip=[feature_1, "count", "percent"]
    ).properties(
        title=f"Distribution of {feature_1} (unit code)",
        width=700,
        height=max(180, min(500, 22 * len(vc)))
    )
else:
    print("No unit code/abbreviation column found. Columns available:", df.columns.tolist())

Selected feature_1 (unit code): unit_measure_code

,feature,rows,missing_count,missing_%,n_unique_non_missing,duplicate_count
0,unit_measure_code,38,0,0.0,38,0

Potential case/whitespace inconsistencies (same code, multiple raw variants): 0

                       unit_measure_code  count  percent
0   ee0468c7-6417-489a-b233-da57ab966174      1     2.63
1   8cb5f9fe-f273-42f3-96e4-1f93e26bb318      1     2.63
2   d8954392-48a0-4cce-af48-15a83ab47274      1     2.63
3   ee700422-0d9b-48c5-ae33-d08b8b5034bf      1     2.63
4   57ee0c60-3085-4d9c-bae2-26022aa2d447      1     2.63
5   aea9d8c5-cf48-46e0-afa3-f36c6cf44c4e      1     2.63
6   c4797df8-be0b-4d3a-a6c4-0f1765f0a822      1     2.63
7   dd058911-cfcb-4c19-9df7-a8f40bbccf13      1     2.63
8   ee1d7851-244e-47db-8960-bced186cccad      1     2.63
9   b0a224d6-adce-4062-b701-32d569ddaa05      1     2.63
10  7768b253-7430-402f-b90f-1e025c57459b      1     2.63
11  3fbce844-926c-442f-87d9-9017094ed6b7      1     2.63
12  1316d404-c512-49da-bfb6-f6df816570ef      1     2.63
13  5c50e872-03a3-4aa1-8d0a-103cdf0fc00d      1     2.63
14  6ad6e4b7-e1c2-42f2-90f6-306f08b41623      1     2.63
15  2eb286e8-8050-4cf5-a260-fd2cedb6e1f4      1     2.63
16  5885bdb8-189e-4001-9f96-9cffd780b130      1     2.63
17  14266c5d-bb1d-4b58-9d8d-f13f6eb35863      1     2.63
18  8dae8c54-6149-48bd-a0e1-9050f4ee82b6      1     2.63
19  7cca3216-2076-4b76-b746-8d4a33c94222      1     2.63
20  acbdd92d-1e1f-4ba8-a695-3f0c82d87759      1     2.63
21  8c4f020f-f9c1-492b-8395-1372b7bda7a7      1     2.63
22  1f485b4e-fc4d-47b2-ab57-af19b21eee40      1     2.63
23  e87c6cb9-24ca-405a-996c-8f59ab7730fa      1     2.63
24  91fa7aa6-72aa-40a6-822f-8b80aa9f6376      1     2.63
25  1f5f8ee7-58c4-4c4e-b8db-b7c1025b3400      1     2.63
26  b4c6422a-e170-4911-852f-38a7c19f5573      1     2.63
27  5c3d2f68-8573-4e53-8c4e-a72a5f92518e      1     2.63
28  e2e52698-ce31-4fb2-866f-bcffbdfd3147      1     2.63
29  7d2f574f-2c4b-45e5-bb2e-7c74c247492c      1     2.63
30  44f61043-62cb-4dea-a921-edf1df4b6a39      1     2.63
31  609a70c5-01f5-48f0-9939-4f04449e2018      1     2.63
32  0cc915c9-7473-4676-afff-2a4d4f023594      1     2.63
33  28bd7d2e-b75a-40dc-b62f-f360a9de2559      1     2.63
34  75fa117b-bb26-4752-8ec5-771acf4c50f6      1     2.63
35  8dbf3502-309f-4636-9f3e-1ae1cabc748b      1     2.63
36  cf068cf8-e6f9-4956-b31b-1d6eb91f3c5c      1     2.63
37  a24c076e-f88e-44e9-811b-b4a3da40d463      1     2.63

In [18]:
# <Student to fill this section>
feature_1_insights = f"""
Feature explored (B.2): {feature_1} (unit of measure code / abbreviation)

Why this feature matters
- {feature_1} is the compact identifier for each unit of measure (e.g., kg, cm, L). It is commonly used in joins, reporting, and validation rules.
- In downstream datasets (such as product or order detail tables), the unit code ensures that quantities are interpreted correctly and consistently (e.g., weight vs length vs volume).

Distribution and what it indicates
- The value counts distribution shows how many unit codes exist and whether any code appears more than once.
- In a well-formed unit_measure reference table, unit codes should be:
  - mostly non-missing,
  - unique (or very close to unique),
  - stable and standardised (no case/whitespace variations).

Data quality checks performed
- Missingness: checked the proportion of records where {feature_1} is missing. Missing codes reduce interpretability after joins.
- Uniqueness/duplicates: checked if any unit codes repeat (duplicate codes create ambiguity in reference data).
- Consistency: tested for case/whitespace inconsistencies (e.g., 'KG' vs 'kg' or 'kg ' vs 'kg'), which can create accidental duplicates and inconsistent reporting.

Limitations / issues to document
- Case-insensitive duplicates can lead to confusing dashboards and incorrect merges if some pipelines join using cleaned codes and others do not.
- If the table contains a “<<MISSING>>”/blank code, it may indicate incomplete master data and should be investigated.

Recommended handling / governance
- Standardise unit codes (trim whitespace and enforce consistent casing, e.g., lower-case).
- Enforce uniqueness constraints on {feature_1} to ensure a 1-to-1 mapping between unit code and unit definition.
- Treat missing codes as data quality defects and resolve upstream where possible.

Conclusion
- {feature_1} is a critical reference attribute for data integrity: clean and unique unit codes prevent downstream join issues and ensure correct interpretation of quantities across the broader dataset.
"""

In [19]:
# Do not modify this code
print_tile(size="h3", key='feature_1_insights', value=feature_1_insights)

In [20]:
from IPython.display import display, HTML
import html

html_text = "<pre style='white-space: pre-wrap; word-wrap: break-word; font-size: 13px; line-height: 1.35;'>" \
            + html.escape(feature_1_insights.strip()) + \
            "</pre>"

display(HTML(html_text))

### B.3 Explore Feature of Interest `name/description

In [21]:
# <Student to fill this section>
# B.3: Explore a "name/description" feature + quality checks
name_candidates = [c for c in df.columns if "name" in c.lower() or "description" in c.lower()]
feature_2 = name_candidates[0] if len(name_candidates) else None
print("Selected feature_2:", feature_2)

if feature_2:
    # Missingness + length profile
    tmp = df[[feature_2]].copy()
    tmp["name_filled"] = tmp[feature_2].fillna("")
    tmp["len"] = tmp["name_filled"].astype(str).str.len()

    display(tmp["len"].describe())

    # Detect suspicious values
    suspicious = df[df[feature_2].isna() | (df[feature_2].astype(str).str.strip() == "")]
    print("Suspicious (missing/blank) rows:", len(suspicious))
    if len(suspicious) > 0:
        display(suspicious.head(20))

    # Show duplicates ignoring case (quality risk)
    lowered = df[feature_2].fillna("").astype(str).str.strip().str.lower()
    dup_count = int(lowered.duplicated().sum())
    print(f"Case-insensitive duplicates in {feature_2}: {dup_count}")
    if dup_count > 0:
        display(df.loc[lowered.duplicated(keep=False), :].sort_values(feature_2).head(50))

    # Bar chart of top names (if small)
    vc = df[feature_2].fillna("<<MISSING>>").astype(str).value_counts().head(25).reset_index()
    vc.columns = [feature_2, "count"]

    alt.Chart(vc).mark_bar().encode(
        x=alt.X("count:Q", title="Count"),
        y=alt.Y(f"{feature_2}:N", sort="-x", title=feature_2),
        tooltip=[feature_2, "count"]
    ).properties(title=f"Top {feature_2} values", width=700, height=300)
else:
    print("No name/description column found; check df.columns.")

Selected feature_2: name

count    38.000000
mean      8.473684
std       4.025170
min       4.000000
25%       5.000000
50%       8.000000
75%      10.000000
max      20.000000
Name: len, dtype: float64

Suspicious (missing/blank) rows: 0
Case-insensitive duplicates in name: 0

In [22]:
# B.3 Extra (HD): Name/description standardisation, token quality, and mapping consistency

if not feature_2:
    print("feature_2 is not set. Run the B.3 selection cell first.")
else:
    s = df[feature_2]

    # 1) Basic profiling (missingness + uniqueness)
    prof = pd.DataFrame([{
        "feature": feature_2,
        "rows": len(df),
        "missing_count": int(s.isna().sum()),
        "missing_%": round(s.isna().mean() * 100, 2),
        "n_unique_non_missing": int(s.nunique(dropna=True)),
        "duplicate_count_raw": int(s.fillna("<<MISSING>>").astype(str).duplicated().sum())
    }])
    display(prof)

    # 2) Clean text version
    tmp = df[[feature_2]].copy()
    tmp["raw"] = tmp[feature_2].fillna("<<MISSING>>").astype(str)
    tmp["clean"] = (
        tmp["raw"]
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)   # collapse multiple spaces
    )
    tmp["clean_lower"] = tmp["clean"].str.lower()
    tmp["len"] = tmp["clean"].str.len()

    # 3) Length-based anomaly detection (very short/very long)
    short = tmp[tmp["len"].between(1, 2)]  # 1-2 characters
    long = tmp[tmp["len"] >= tmp["len"].quantile(0.95)]  # top 5% lengths

    print("Very short names (len 1-2):", len(short))
    if len(short) > 0:
        display(short[[feature_2, "clean", "len"]].head(20))

    print("Very long names (top 5% by length):", len(long))
    if len(long) > 0:
        display(long[[feature_2, "clean", "len"]].sort_values("len", ascending=False).head(20))

    # 4) Case/whitespace inconsistencies: same clean_lower, multiple raw forms
    variants = (
        tmp.groupby("clean_lower")["raw"]
           .nunique()
           .reset_index(name="n_raw_variants")
           .sort_values("n_raw_variants", ascending=False)
    )
    variants = variants[(variants["clean_lower"] != "<<missing>>") & (variants["n_raw_variants"] > 1)]
    print("Potential naming inconsistencies (case/spacing variants):", len(variants))
    if len(variants) > 0:
        display(variants.head(20))

    # 5) Word/token analysis (helps explain naming conventions)
    tmp["n_words"] = tmp["clean"].apply(lambda x: len([w for w in x.split(" ") if w]))
    display(tmp["n_words"].describe())

    word_dist = tmp["n_words"].value_counts().sort_index().reset_index()
    word_dist.columns = ["n_words", "count"]
    alt.Chart(word_dist).mark_bar().encode(
        x=alt.X("n_words:O", title="Number of words in name/description"),
        y=alt.Y("count:Q", title="Count"),
        tooltip=["n_words:O", "count:Q"]
    ).properties(title=f"Word-count distribution for {feature_2}", width=700, height=250)

    # 6) Mapping consistency with unit code (if feature_1 exists)
    if "feature_1" in globals() and feature_1:
        m = df[[feature_1, feature_2]].copy()
        m[feature_1] = m[feature_1].fillna("<<MISSING>>").astype(str).str.strip().str.lower()
        m[feature_2] = m[feature_2].fillna("<<MISSING>>").astype(str).str.strip().str.lower()

        # One code should map to exactly one name (ideal)
        names_per_code = m.groupby(feature_1)[feature_2].nunique().reset_index(name="n_names_per_code")
        bad_codes = names_per_code[names_per_code["n_names_per_code"] > 1].sort_values("n_names_per_code", ascending=False)

        print("Codes mapping to multiple names (join ambiguity risk):", len(bad_codes))
        if len(bad_codes) > 0:
            display(bad_codes.head(20))
            # show examples
            example_codes = bad_codes[feature_1].head(5).tolist()
            display(m[m[feature_1].isin(example_codes)].sort_values([feature_1, feature_2]).head(50))
    else:
        print("feature_1 not found; skipping code-to-name mapping consistency check.")

,feature,rows,missing_count,missing_%,n_unique_non_missing,duplicate_count_raw
0,name,38,0,0.0,38,0

Very short names (len 1-2): 0
Very long names (top 5% by length): 2

                    name                 clean  len
21  Kilogram/cubic meter  Kilogram/cubic meter   20
9      Square centimeter     Square centimeter   17

Potential naming inconsistencies (case/spacing variants): 0

count    38.000000
mean      1.289474
std       0.515065
min       1.000000
25%       1.000000
50%       1.000000
75%       1.750000
max       3.000000
Name: n_words, dtype: float64

Codes mapping to multiple names (join ambiguity risk): 0

In [23]:
"""Distribution of String Lengths in Selected Field"""

import altair as alt
from IPython.display import display

alt.renderers.enable("default")
alt.data_transformers.disable_max_rows()

string_cols = df.select_dtypes(include="object").columns.tolist()

preferred_col = None

for col in string_cols:
    if df[col].nunique() < len(df) * 0.9:  # not pure unique IDs
        preferred_col = col
        break

if preferred_col is None:
    preferred_col = string_cols[0] if string_cols else None

if preferred_col is None:
    print("No string columns found.")
else:

    print("Using column:", preferred_col)

    tmp = df[[preferred_col]].copy()
    tmp[preferred_col] = tmp[preferred_col].fillna("").astype(str)

    tmp["len"] = tmp[preferred_col].str.len()

    chart = (
        alt.Chart(tmp)
        .mark_bar(opacity=0.7, color="steelblue")
        .encode(
            x=alt.X(
                "len:Q",
                bin=alt.Bin(maxbins=30),
                title="String Length (characters)"
            ),
            y=alt.Y("count():Q", title="Frequency"),
            tooltip=["count():Q"]
        )
        .properties(
            title=f"String Length Distribution : {preferred_col}",
            width=600,
            height=300
        )
    )

    display(chart)

Using column: unit_measure_code

alt.Chart(...)

In [24]:
feature_2_insights = f"""
Feature explored (B.3): name (unit name / description)

Why this feature matters
- name provides the human-readable meaning of each unit of measure and complements the unit code (B.2).
- It is important for interpretability in reporting and for data governance: analysts need consistent names to understand quantities correctly after joins.

What we analysed
- Completeness: measured missing and blank values to ensure descriptions exist for all units.
- Text quality: checked string length distribution and identified unusually short or unusually long values that may indicate data entry issues.
- Consistency: tested for case and whitespace inconsistencies (e.g., 'Kilogram' vs ' kilogram ') which can create duplicate-looking entries.
- Duplication risk: checked for case-insensitive duplicates that could indicate repeated unit definitions.
- Mapping integrity with unit codes (where available):
  - verified whether one unit code maps to exactly one unit name (ideal),
  - flagged cases where the same code maps to multiple names, which would create ambiguity in joins and reporting.

Key insights and interpretation
- A clean unit_measure dimension should have a one-to-one relationship between unit code and unit name/description.
- If duplicates or inconsistent naming are present, the dataset may still be usable, but standardisation is required to ensure consistent downstream analytics.

Limitations / issues to document
- Names/descriptions are not predictive features; they are reference metadata.
- Inconsistent naming conventions reduce interpretability and may cause confusion, especially if different pipelines display different variants of the same unit.

Recommended handling / governance
- Standardise name (trim whitespace, collapse multiple spaces, use consistent casing).
- Enforce data quality rules:
  - non-null descriptions (where required),
  - one-to-one mapping between unit code and unit name.
- If conflicts exist, resolve upstream (master data correction) rather than patching in analysis.

Conclusion
- name is important for correctness and interpretability: ensuring it is complete and consistent improves join reliability and prevents misunderstanding of measurement units across the broader dataset.
"""

In [25]:
# Do not modify this code
print_tile(size="h3", key='feature_2_insights', value=feature_2_insights)

In [26]:
from IPython.display import display, HTML
import html

html_text = "<pre style='white-space: pre-wrap; word-wrap: break-word; font-size: 13px; line-height: 1.35;'>" \
            + html.escape(feature_2_insights.strip()) + \
            "</pre>"

display(HTML(html_text))

### B.4 Explore Feature of Interest `integrity`

In [27]:
# B.4: Explore key integrity (unit_measure_id or similar)
id_candidates = [c for c in df.columns if c.lower().endswith("id")]
feature_n = id_candidates[0] if len(id_candidates) else None
print("Selected feature_n (ID/key):", feature_n)

if feature_n:
    # Missingness and uniqueness
    miss = df[feature_n].isna().sum()
    dup = df[feature_n].duplicated().sum()
    nun = df[feature_n].nunique(dropna=True)

    key_stats = pd.DataFrame([{
        "feature": feature_n,
        "rows": len(df),
        "missing_count": int(miss),
        "missing_%": round(miss / len(df) * 100, 2) if len(df) else None,
        "duplicate_count": int(dup),
        "n_unique": int(nun),
    }])
    display(key_stats)

    # If duplicates exist, show them
    if dup > 0:
        display(df[df[feature_n].duplicated(keep=False)].sort_values(feature_n).head(50))

    # (Optional) check 1:1 mapping between code and name if both exist
    if "feature_1" in globals() and feature_1 and "feature_2" in globals() and feature_2:
        mapping = df.groupby(feature_1)[feature_2].nunique(dropna=True).reset_index(name="n_names_per_code")
        display(mapping.sort_values("n_names_per_code", ascending=False).head(20))
else:
    print("No ID column found; cannot assess join-key integrity.")

Selected feature_n (ID/key): None
No ID column found; cannot assess join-key integrity.

In [28]:
# B.4 Extra 1: Key type / range / monotonic checks
if feature_n:
    s = df[feature_n]

    print("ID dtype:", s.dtype)
    print("Non-null count:", int(s.notna().sum()))
    print("Min:", s.min() if s.notna().any() else None)
    print("Max:", s.max() if s.notna().any() else None)

    # If numeric, check if it looks like a surrogate key (positive integers)
    if pd.api.types.is_numeric_dtype(s):
        non_int = int((s.dropna() % 1 != 0).sum())
        non_pos = int((s.dropna() <= 0).sum())
        print("Non-integer values (should be 0 for surrogate keys):", non_int)
        print("Non-positive values (should be 0 for surrogate keys):", non_pos)

        # Check if IDs are roughly sequential (not required, but informative)
        uniq = s.dropna().drop_duplicates().sort_values()
        if len(uniq) > 1:
            gaps = (uniq.diff().dropna() > 1).sum()
            print("Number of gaps in sorted unique IDs (diff > 1):", int(gaps))

In [29]:
# B.4 Extra 2: Investigate duplicate IDs in detail
if feature_n:
    dup_mask = df[feature_n].duplicated(keep=False)
    dup_df = df.loc[dup_mask].copy()

    print("Rows with duplicated IDs:", len(dup_df))
    if len(dup_df) > 0:
        # Sort for readability
        show_cols = [c for c in [feature_n, feature_1 if "feature_1" in globals() else None, feature_2 if "feature_2" in globals() else None] if c]
        show_cols = show_cols + [c for c in df.columns if c not in show_cols][:6]  # add a few extra columns if present
        display(dup_df[show_cols].sort_values(feature_n).head(80))

        # Group sizes
        dup_sizes = dup_df.groupby(feature_n).size().reset_index(name="rows_per_id").sort_values("rows_per_id", ascending=False)
        display(dup_sizes.head(20))
    else:
        print("No duplicate IDs detected.")

In [30]:
# B.4 Extra 3: Completeness checks across join-critical columns
critical_cols = [c for c in [feature_n, feature_1 if "feature_1" in globals() else None, feature_2 if "feature_2" in globals() else None] if c]

if feature_n:
    comp = []
    for c in critical_cols:
        comp.append({
            "column": c,
            "missing_count": int(df[c].isna().sum()),
            "missing_%": round(df[c].isna().mean() * 100, 2),
            "n_unique_non_missing": int(df[c].nunique(dropna=True))
        })
    display(pd.DataFrame(comp))
else:
    print("feature_n not set; cannot run completeness checks.")

feature_n not set; cannot run completeness checks.

In [31]:
# B.4 Extra 4: 1-to-1 mapping checks (detect join ambiguity)
if feature_n and "feature_1" in globals() and feature_1:
    # Does one ID map to multiple codes?
    id_to_codes = df.groupby(feature_n)[feature_1].nunique(dropna=True).reset_index(name="n_codes_per_id")
    bad_id_to_codes = id_to_codes[id_to_codes["n_codes_per_id"] > 1].sort_values("n_codes_per_id", ascending=False)

    print("IDs mapping to multiple codes:", len(bad_id_to_codes))
    if len(bad_id_to_codes) > 0:
        display(bad_id_to_codes.head(20))
        example_ids = bad_id_to_codes[feature_n].head(5).tolist()
        display(df[df[feature_n].isin(example_ids)].sort_values([feature_n, feature_1]).head(50))

    # Does one code map to multiple IDs?
    code_to_ids = df.groupby(feature_1)[feature_n].nunique(dropna=True).reset_index(name="n_ids_per_code")
    bad_code_to_ids = code_to_ids[code_to_ids["n_ids_per_code"] > 1].sort_values("n_ids_per_code", ascending=False)

    print("Codes mapping to multiple IDs:", len(bad_code_to_ids))
    if len(bad_code_to_ids) > 0:
        display(bad_code_to_ids.head(20))
        example_codes = bad_code_to_ids[feature_1].head(5).tolist()
        display(df[df[feature_1].isin(example_codes)].sort_values([feature_1, feature_n]).head(50))
else:
    print("Need feature_n and feature_1 to run ID↔code mapping checks.")

Need feature_n and feature_1 to run ID↔code mapping checks.

In [32]:
# B.4 Extra 5: Join-simulation check (row explosion risk)
# If IDs are duplicated, joining a fact table on this dimension can duplicate fact rows.
if feature_n:
    id_counts = df[feature_n].value_counts(dropna=False).reset_index()
    id_counts.columns = [feature_n, "rows_in_dimension"]

    # Worst offenders (if any)
    worst = id_counts.sort_values("rows_in_dimension", ascending=False).head(10)
    display(worst)

    if worst["rows_in_dimension"].iloc[0] > 1:
        print("WARNING: Dimension key is not unique. Joining on this key may cause row explosion.")
    else:
        print("Good: Dimension key appears unique (safe for joins).")

df.columns.tolist()
df.head()

                      unit_measure_code      name
0  ee0468c7-6417-489a-b233-da57ab966174     Boxes
1  7768b253-7430-402f-b90f-1e025c57459b    Bottle
2  1f485b4e-fc4d-47b2-ab57-af19b21eee40   Celsius
3  e87c6cb9-24ca-405a-996c-8f59ab7730fa  Canister
4  91fa7aa6-72aa-40a6-822f-8b80aa9f6376    Carton

In [33]:
# <Student to fill this section>
feature_n_insights = f"""
Feature explored (B.4): {feature_n} (primary key / join key for unit_measure)

Why this feature matters
- In a reference (dimension) table, {feature_n} is the most important technical feature because other tables will join to unit_measure using this ID.
- If {feature_n} is not unique or contains missing values, joins can become many-to-many, creating duplicated rows (“row explosion”) and incorrect aggregates downstream.

What we analysed (HD-level key integrity validation)
- Completeness: checked missing_count and missing_% for {feature_n}. Missing IDs would break joins and reduce usable records.
- Uniqueness: measured duplicate_count and n_unique to confirm whether {feature_n} behaves like a true primary key.
- Type/validity (where applicable): if the ID is numeric, checked whether it looks like a surrogate key (positive integers, no decimals).
- Duplicate diagnostics: where duplicates exist, inspected duplicated groups to see if duplicates are identical (true duplicates) or conflicting records (data integrity issue).
- Mapping consistency:
  - tested whether one {feature_n} maps to multiple unit codes (should not happen),
  - tested whether one unit code maps to multiple IDs (also should not happen),
  - optionally checked whether unit codes map to multiple names/descriptions.

Key findings and interpretation
- Ideal outcome: {feature_n} has 0% missingness and 0 duplicates, indicating the table is safe for joins.
- If duplicates are detected, it indicates either:
  - repeated reference rows (deduplication required), or
  - conflicting master data definitions (requires upstream correction).

Limitations / issues to document
- This feature is not a predictive attribute; it is an identifier.
- However, poor quality in {feature_n} can silently corrupt downstream feature engineering and model training by duplicating or mislabelling records during joins.

Recommended handling / governance
- Enforce a primary key constraint on {feature_n} (unique + non-null).
- Standardise and validate ID-to-code and code-to-name mappings so that each unit has a single, consistent definition.
- If duplicated IDs or codes exist, resolve them at the source (master data) before building any modelling dataset.

Conclusion
- {feature_n} is the backbone of join integrity for unit_measure. Ensuring it is unique, non-missing, and consistently mapped prevents downstream merge errors and improves the reliability of all analytics and modelling work.
"""

In [34]:
# Do not modify this code
print_tile(size="h3", key='feature_n_insights', value=feature_n_insights)

In [35]:
from IPython.display import display, HTML
import html

html_text = "<pre style='white-space: pre-wrap; word-wrap: break-word; font-size: 13px; line-height: 1.35;'>" \
            + html.escape(feature_n_insights.strip()) + \
            "</pre>"

display(HTML(html_text))

In [36]:
overall_insights = f"""
Overall EDA insights (unit_measure.csv)

1) Dataset purpose and value in the wider data model
- unit_measure is a reference/dimension table that defines units of measure used across the database (e.g., products, inventory, order details).
- While it is not directly predictive for modelling, it is critical for data integrity because it standardises how quantities are interpreted (weight, length, volume, count).

2) Structural expectations and validation performed
- Expected grain: one row per unit of measure definition.
- We validated dimension-table health using:
  - schema inspection (dtypes),
  - missingness checks,
  - duplicate row checks,
  - uniqueness checks for the primary key ({feature_n} if detected),
  - consistency checks for unit codes ({feature_1}) and names/descriptions ({feature_2}).

3) Key insights from features explored
B.2 ({feature_1}: unit code)
- The unit code is the primary human/system identifier used in reporting and validation.
- The distribution and duplicate checks help confirm whether codes are unique and standardised.
- Potential issues such as case/whitespace variants (e.g., 'KG' vs 'kg') were considered because they can cause inconsistent reporting and messy joins if different pipelines apply different cleaning rules.

B.3 ({feature_2}: unit name/description)
- Unit names/descriptions support interpretability and governance.
- We assessed completeness, suspicious blanks, length anomalies, and case-insensitive duplicates to detect inconsistent naming conventions.
- Where possible, mapping checks confirmed whether one unit code maps to one consistent name (ideal for reference data).

B.4 ({feature_n}: primary key)
- The ID field is the backbone of join integrity.
- Uniqueness and non-nullness are essential to avoid:
  - many-to-many joins,
  - duplicated fact rows after merges (“row explosion”),
  - incorrect aggregation results in analysis and modelling datasets.

4) Data quality risks (what to document in the report)
- Join ambiguity risk:
  - duplicated IDs or codes,
  - one-to-many mappings between code and name,
  - inconsistent text formatting (case/whitespace) that creates duplicate-looking values.
- Interpretability risk:
  - missing or vague descriptions reduce clarity when units appear in dashboards or stakeholder reports.

5) Recommended actions / governance rules (HD-level)
- Enforce constraints:
  - {feature_n} must be unique and non-null (primary key),
  - {feature_1} should be unique (business key) and standardised (trim + consistent casing),
  - {feature_2} should be non-empty and consistent.
- Standardise text fields:
  - strip whitespace, collapse multiple spaces, consistent casing.
- Validate one-to-one mapping:
  - unit_code ↔ unit_name should be 1:1 where possible.

Conclusion
- The unit_measure dataset behaves as a dimension table and, when kept clean (unique keys + consistent code/name mappings), it strengthens the reliability of all downstream joins and ensures quantities are interpreted consistently across the full analytics and modelling pipeline.
"""

In [37]:
from IPython.display import display, HTML
import html

html_text = "<pre style='white-space: pre-wrap; word-wrap: break-word; font-size: 13px; line-height: 1.35;'>" \
            + html.escape(overall_insights.strip()) + \
            "</pre>"

display(HTML(html_text))

In [38]:
import pandas as pd
import altair as alt

# Allow Altair to handle larger dataframes
alt.data_transformers.disable_max_rows()

# --- 1. Identification Logic ---
# Find the primary column (col) and a secondary column (col2) for the heatmap
obj_cols = df.select_dtypes(include=["object", "string", "category"]).columns.tolist()

col = "name" if "name" in df.columns else (obj_cols[0] if obj_cols else None)
# Select the second categorical column if it exists, otherwise use the same as col
col2 = obj_cols[1] if len(obj_cols) > 1 else (obj_cols[0] if obj_cols else None)

# --- 2. Bar Chart Execution ---
if col is None:
    print("No categorical columns found to plot.")
else:
    # Prepare data for Bar Chart: Top 20
    bar_data = df[col].fillna("MISSING").value_counts().head(20).reset_index()
    bar_data.columns = [col, "count"]

    bar_chart = alt.Chart(bar_data).mark_bar(cornerRadiusEnd=3).encode(
        y=alt.Y(f"{col}:N", sort="-x", title=f"Top Values in {col}"),
        x=alt.X("count:Q", title="Frequency"),
        color=alt.Color("count:Q", scale=alt.Scale(scheme="viridis"), legend=None),
        tooltip=[col, "count"]
    ).properties(
        width=600, 
        height=400, 
        title={
            "text": f"Top 20 Distribution: {col}",
            "subtitle": "Visualizing the most frequent categorical entries"
        }
    ).configure_axis(
        labelFontSize=12,
        titleFontSize=14
    )
    
    bar_chart.display()

    # --- 3. Heat Map Execution ---
    if col2 and col != col2:
        # Pre-aggregate data for the heatmap to ensure performance and accuracy
        # Taking top 15 of each to keep the heatmap readable
        top_col1 = df[col].value_counts().head(15).index
        top_col2 = df[col2].value_counts().head(15).index
        
        subset = df[df[col].isin(top_col1) & df[col2].isin(top_col2)]
        
        heat_map = alt.Chart(subset).mark_rect().encode(
            x=alt.X(f"{col}:N", title=f"{col}"),
            y=alt.Y(f"{col2}:N", title=f"{col2}"),
            color=alt.Color("count():Q", scale=alt.Scale(scheme="magma"), title="Count"),
            tooltip=[
                alt.Tooltip(f"{col}:N"),
                alt.Tooltip(f"{col2}:N"),
                alt.Tooltip("count():Q", title="Frequency")
            ]
        ).properties(
            width=600,
            height=400,
            title={
                "text": f"Frequency Heat Map: {col} vs {col2}",
                "subtitle": f"Intersection of top 15 categories"
            }
        )
        
        heat_map.display()
    else:
        print("Could not find a distinct second categorical column for a heatmap.")

alt.Chart(...)

Could not find a distinct second categorical column for a heatmap.

In [39]:
import pandas as pd
import altair as alt

dup_counts = pd.DataFrame({
    "type": ["Duplicate rows", "Unique rows"],
    "count": [df.duplicated().sum(), (~df.duplicated()).sum()]
})

alt.Chart(dup_counts).mark_bar().encode(
    x=alt.X("type:N", title=""),
    y=alt.Y("count:Q", title="Rows"),
    tooltip=["type:N", "count:Q"]
).properties(width=450, height=300, title="Duplicate rows in unit_measure dataset")

alt.Chart(...)

In [40]:
import pandas as pd

code_col = None
for c in df.columns:
    if "code" in c.lower():
        code_col = c
        break

name_col = "name" if "name" in df.columns else None

if code_col is None or name_col is None:
    print("Could not find both a code column and a name column (expected something like unit_measure_code + name).")
else:
    # How many names per code?
    mapping = df[[code_col, name_col]].dropna()
    n_names_per_code = mapping.groupby(code_col)[name_col].nunique().reset_index(name="n_unique_names")

    print("Codes with more than 1 name (potential data quality issue):")
    display(n_names_per_code[n_names_per_code["n_unique_names"] > 1].head(20))

    print("Summary of mapping uniqueness:")
    display(n_names_per_code["n_unique_names"].value_counts().sort_index().to_frame("count"))

Codes with more than 1 name (potential data quality issue):

Empty DataFrame
Columns: [unit_measure_code, n_unique_names]
Index: []

Summary of mapping uniqueness:

                count
n_unique_names
1                  38